### ISSUE TITLE
Crashes on Ubuntu 22.04

### ISSUE THREAD

**Issue by skiselkov** [xpilot-project/xpilot#101]
Attempting to launch the standalone xPilot client on Ubuntu 22.04 immediately crashes due to a segmentation fault. Backtrace is attached
[bt.txt](https://github.com/xpilot-project/xpilot/files/8743461/bt.txt)
.

**Comment by skiselkov** [comment]
Forgot to include terminal output, so here it is
[stdout.txt](https://github.com/xpilot-project/xpilot/files/8743476/stdout.txt)
:

**Comment by skiselkov** [comment]
Found a workaround that you might want to implement: the product depends on the OS-shipped libcrypto, which isn't being shipped in the squashfs in the app distribution. You might want to include it to avoid this external dependency. I've found that by unpacking the squashfs and throwing in the contents of the Ubuntu 20.04 libssl1.1 deb package, the app works and boots fine.

**Comment by wiggleforlife** [comment]
For those who would like more assistance with this, a Fedora user was able to use this after installing `binutils`
```bash
curl -o libssl1.1_1.1.1f-1ubuntu2.13_amd64.deb http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.13_amd64.deb
ar x libssl1.1_1.1.1f-1ubuntu2.13_amd64.deb
tar -xf data.tar.xz
/path/to/appimage --appimage-extract
cd squashfs-root/usr/lib
mv ../../../usr/lib/x86_64-linux-gnu .
cd ../..
./AppRun
```

**Comment by janstav** [comment]
Thanks @wiggleforlife and @manymiles, but is there a specific procedure for ubuntu 22? I am new on ubuntu, tryed to copy the lines into terminal, but I am unable to to proceed
Thank you

**Comment by wiggleforlife** [comment]
@janstav I'm going to go out on a limb here and say you're having trouble with `ar`. If this is the case, run `sudo apt-get install binutils`. 

If this is not the issue, we need more information. Is there an error being provided or is there some other problem?

**Comment by Bombardier-C-Kram** [comment]
For anyone having any problems with the solution above, I think that the link provided no longer exists. A drop in replacement is security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1-1ubuntu2.1~18.04.20_amd64.deb

Making the solution:

```
curl -o libssl.deb http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1-1ubuntu2.1~18.04.20_amd64.deb
ar x libssl.deb
tar -xf data.tar.xz
/path/to/appimage --appimage-extract
cd squashfs-root/usr/lib
mv ../../../usr/lib/x86_64-linux-gnu/* .
cd ../..
./AppRun
```

**Comment by justinshannon** [comment]
This should be resolved in beta 35.
