### ISSUE TITLE
beta.34 crashed on MacOS Catalina

### ISSUE THREAD

**Issue by mzmznasipadang** [xpilot-project/xpilot#103]
Hi, xPilot Crashed when x-plane loaded iniBuilds A310 / A300 in any airport, but works well with IXEG 737 and LevelUp 737,

Below I attached the Log, it's run on beta.32 but also crashed on beta.34
[Log.txt](https://github.com/xpilot-project/xpilot/files/8792753/Log.txt)

**Comment by justinshannon** [comment]
https://beta.xpilot-project.org/#/xplane-crash

**Comment by mzmznasipadang** [comment]
bro… isn’t I attached the log.txt aswell?

**Comment by mzmznasipadang** [comment]
Oh shot! I will re-install X-Plane again, I will open this if I have encountered it again!
