### ISSUE TITLE
PTT Not Working on WIndows

### ISSUE THREAD

**Issue by erictg** [xpilot-project/xpilot#104]
Hi,
Push to talk is not allowing me transmit voice. I have it correctly configured in xp11. I set the option to show the green text in the sim when PTT is active. The text is showing but in the xpilot client the transmit bar is not being highlighted. I also verified that COM1 is on for transmit and receive in the helicopter that I'm using. Additionally I tried enabling the override Contact ATC button but that did not work either.

**Comment by erictg** [comment]
Running XPilot as administrator solved this problem. Did I miss this in the documentation?

**Comment by justinshannon** [comment]
Running xPilot as an administrator shouldn't be necessary - but if it fixed it for you, that's great.
