### ISSUE TITLE
TLS initialization failed

### ISSUE THREAD

**Issue by bogdan2011** [xpilot-project/xpilot#11]
![Screenshot 2021-12-02 233121](https://user-images.githubusercontent.com/7944954/144645916-51d3e6d4-9b77-4e39-bac7-409872b4b9b6.png)

I'm getting this error when running beta 6 on my Windows 11 machine. The Linux version works fine. Non-beta version works without issues. I have also tried disabling firewall/defender without success.

**Comment by justinshannon** [comment]
Hi, I also commented on your forum post. Can you download these replacement OpenSSL libraries and put them in the folder where the xPilot client is installed? It should ask you if you want to overwrite existing files, click "Yes".

Let me know your results after doing this.

https://drive.google.com/file/d/1Qo9q3MJbpZgGPcC0AkW7uD7V8CsPSK62/view?usp=sharing

**Comment by bogdan2011** [comment]
Yes everything works fine with the replacement libraries.
