### ISSUE TITLE
SELCAL for MSFS

### ISSUE THREAD

**Issue by juliansebline** [xpilot-project/xpilot#111]
Hello,

I'm from FBW development team.

I'd like to implement the SELCAL feature. One person from the team will make a custom sound whereas I will be wiring everything with the third parties.

The data structure would be a struct with selcal field (uint8_t). You would set it to 1 to trigger it then I'd send 0 back once the call is accepted or reseted.

Another addition, if you wish, we could control COM1 and COM2 volume via either the application or via the volume knobs in the sim.
If so, another two uint8_t fields will have to be added in the structure.

I have piece of SimConnect code prepared for all that since I have integrated it with another third party.

Thank you!

Julian

**Comment by DominikTV** [comment]
I think you are searching vPilot since xPilot 

> ...is a cross-platform **X-Plane 11** pilot client for VATSIM...

**Comment by justinshannon** [comment]
xPilot is for X-Plane only. You'll want to reach out to the **vPilot** developer instead.
