### ISSUE TITLE
beta 35 will not connect

### ISSUE THREAD

**Issue by DevonFly** [xpilot-project/xpilot#114]
Have just upgraded to 35. Have within last 30 minutes loaded x-plane & filed a flight plan as usual. Connect button is greyed out so unable to connect to vatsim. Have tried closing xpilot & opening again several times; also have tried chnging servers in settings.
![xpilot error 10-9-2022](https://user-images.githubusercontent.com/53476922/189490373-0f742c13-7a48-400d-b926-2f3f58eaed2f.jpg)

**Comment by DevonFly** [comment]
Looks as if it did not download properly. Have re-installed and is ok

**Comment by justinshannon** [comment]
If after upgrading to beta 35 you're unable to get the xPilot plugin to load (the X-Plane log.txt will print this error: `Error Code = 126 : The specified module could not be found.`), you will need to manually download and install the X-Plane 11 variant of beta 35. 

https://github.com/xpilot-project/xpilot/releases/tag/v2.0.0-beta.35
