### ISSUE TITLE
CSL Crash

### ISSUE THREAD

**Issue by MucahidTR33** [xpilot-project/xpilot#115]
Hello, after the latest update that came of in april 4th I couldn`t no longer fly on Vatsim because I keep getting CSL erors even though I don`t have any type of plugin for the CSL.
After 30-40 minutes of flying X plane 11 automatically crashes and the log.txt file says it has something do with the CSL`s!
I`ve unistalled and installed xpilot many times but it never helped!
Have anyone experienced this before?

**Comment by justinshannon** [comment]
Please provide the appropriate log files: https://beta.xpilot-project.org/#/xplane-crash

**Comment by MucahidTR33** [comment]
> Please provide the appropriate log files: https://beta.xpilot-project.org/#/xplane-crash

I can’t see anything about x pilot crash, just CSL warnings?

**Comment by justinshannon** [comment]
If the log doesn’t explicitly say a plugin caused X-Plane to crash, historically that meant it was a video driver crash. If you have the logs, upload them. Otherwise there’s nothing else I can do to help you.
