### ISSUE TITLE
Reported Altitude

### ISSUE THREAD

**Issue by becas22** [xpilot-project/xpilot#116]
I was controlling and had a plane showing FL346. I asked to confirm altitude and altimeter setting, which he replied FL340, standard.
He mentioned he was flying XP12 and that it was due to cold temperature effect.

xPilot should report pressure altitude, not true altitude

**Comment by justinshannon** [comment]
Known issue, should be fixed in the next release.

**Comment by NNowakowski** [comment]
Any update on this? Controllers are constantly telling me that I'm too high and that I should descent down to the cleared altitude.
