### ISSUE TITLE
xPilot w/ X-Plane12.00b3 Mapped Flight Path Display Affected

### ISSUE THREAD

**Issue by slowrunner** [xpilot-project/xpilot#117]
Strange Issue: Mapped Flight Path affected by xPilot in X-Plane 12b3

Description: 
- Full flight path not displayed in x-plane12 map window when using xPilot during a 48 minute flight
- Repeated connect/disconnect "ate" more of displayed flight path

Config:

- OS: Mac OS Monterey 12.5.1 on 2018 Mac Mini
- Graphics: Radeon RX580 8GB in eGPU
- X-Plane12.00b3
- xPilot v2.0.0-beta.35 

After flight and After Disconnect:
![1_After_Flight_Disconnected](https://user-images.githubusercontent.com/8950202/190724441-1960fac6-e49d-4816-a4c9-5a89e1ff6b26.jpg)

Brief flash of whole flight during reconnect to VATSIM:
![2_During Connect](https://user-images.githubusercontent.com/8950202/190724509-b034472c-5718-477f-b5d6-1dabea70e79e.jpg)

Partial flight path displayed after re-connect:
![3_Re-Connected](https://user-images.githubusercontent.com/8950202/190724584-672abae6-a959-4098-b6d8-3226a3907009.jpg)

Even more flight path "eaten" by repeated disconnects:
![4_Re-Disconnected](https://user-images.githubusercontent.com/8950202/190724645-79038ec3-631e-43e1-89d3-2b522f3e1b04.jpg)

[Log.txt](https://github.com/xpilot-project/xpilot/files/9586991/Log.txt)

Also posted at https://forums.x-plane.org/index.php?/forums/topic/272252-x-pilot-for-vatsim/&do=findComment&comment=2412368

**Comment by justinshannon** [comment]
xPilot doesn’t control how paths are drawn on the map. I’d suggest you file an X-Plane bug report.
