### ISSUE TITLE
Make it easier to swap between X-Plane Versions

### ISSUE THREAD

**Issue by AIR-BOGO** [xpilot-project/xpilot#118]
So this is gonna be an issue for a while, and I find it redundant to have to reinstall xpilot anytime I want to swap between xplane 11 and xplane 12. is there a plan to combine compatibility into one application? or an easy way to swap without having to restart the sim because you forgot you had the other version of the client installed?

**Comment by justinshannon** [comment]
This will be addressed in the next release.
