### ISSUE TITLE
[Suggestion] Add .wx/.metar command to xPilot interface

### ISSUE THREAD

**Issue by ChrisXPP** [xpilot-project/xpilot#12]
Hi,

is it (technically) possible to add the .wx/.metar command to the xPilot interface, too?
This way you won't need to switch between interface and main application to retrieve weather information...

**Comment by justinshannon** [comment]
The `.wx` and `.metar` commands already exist. They work in both the xPilot client and Text Message Console in X-Plane.

**Comment by ChrisXPP** [comment]
Just wonder why I haven't tried this for myself, yet... 
You're right, works perfectly in both the xPilot client and text message console. :-)

"Issue" closed.
