### ISSUE TITLE
XP12: xpilot/ai_controlled = 1 even when not connected to vatsim? 

### ISSUE THREAD

**Issue by IBAV8N** [xpilot-project/xpilot#120]
Ubuntu 20.04 version.
When I start XP12 not connected to vatsim,  xpilot/ai_controlled = 1 and cannot be edited.
If I then connect and then disconnect from vatsim using the external app,  xpilot/ai_controlled = 0.
It seems to me that 'xpilot/ai_controlled' should equal  zero  until connected to the vatsim network.  Otherwise plugins like LiveTraffic wil not work.
I'm guessing that this is a bug?

**Comment by justinshannon** [comment]
The `xpilot/ai_controlled` dataref does not inherently restrict other multiplayer/traffic plugins from working. The dataref value simply indicates whether or not xPilot has control over the TCAS targets. X-Plane only allows one plugin to control the TCAS targets at once. You can always release control of TCAS and allow another plugin to take over through the plugin menu.
