### ISSUE TITLE
Feature request: tune unicom via click

### ISSUE THREAD

**Issue by jonaseberle** [xpilot-project/xpilot#121]
It would be very convenient to be able to tune Unicom 122.800 via:

* the app
* the X-Plane plugin window "Nearby ATC"

I suggest to have that entry always available, on the very bottom, in a group "Unicom".

**Comment by justinshannon** [comment]
The feature has been added to the Nearby ATC window in X-Plane. 

This will not be added to the client application at this time. I don't have a good way to add it to the UI at this time without some major refactoring.
