### ISSUE TITLE
Feature request: tune COM2 via the X-Plane plugin window "Nearby ATC"

### ISSUE THREAD

**Issue by jonaseberle** [xpilot-project/xpilot#122]
Currently, it is possible to tune COM1 by clicking the icon  in the X-Plane plugin window "Nearby ATC":
![image](https://user-images.githubusercontent.com/1678001/192165810-424335d8-7008-4dac-9300-f68573783acb.png)

We can tune COM2, too in the app (on right click):
![image](https://user-images.githubusercontent.com/1678001/192165906-52d414ec-6d7b-42fe-a1e0-09ebbb054aca.png)

It would be great to be able to tune COM2 in the X-Plane plugin window "Nearby ATC" as well.

I don't know what the technical possibilities are. Via right click? Or maybe via a second icon.

Background:
I like the convenience of "cheating" with the "Nearby ATC" window (I have it bound to the ENTER key). But I also like pre-selecting the next stations to switch via switching the COM receiver. Actually, if I would select it manually, I would probably pre-tune the next station as "standby" frequency on COM1, but I am not sure if a "standby" freq can be controlled by a plugin. Being able to pre-tune "standby" would obviously also be amazing.

**Comment by justinshannon** [comment]
This will be made available in the next release.

![X-Plane_xfSsqJorxL](https://user-images.githubusercontent.com/3221191/196077269-79a13d95-b54c-40ae-8e33-9d0ca0e697c7.png)

**Comment by justinshannon** [comment]
Support for tuning COM2 in the X-Plane nearby ATC window will be available in the next release.

There's really not a good way to add this to the client UI without cluttering it, so it will not be added to the client for now.
