### ISSUE TITLE
Beta 35 hangs XP12b5

### ISSUE THREAD

**Issue by donks** [xpilot-project/xpilot#123]
After updating XP12 from beta 4 to beta 5, xpilot hangs XP12 when trying to start a new flight.
Last log entry is:
`The plugin xPilot 2.0.0-beta.35 is setting global TCAS override to 1.`

**Comment by justinshannon** [comment]
As also requested in Discord, please upload your full X-Plane log.txt.

**Comment by donks** [comment]
See attached.
[Log.txt](https://github.com/xpilot-project/xpilot/files/9703990/Log.txt)

**Comment by justinshannon** [comment]
It looks like it's hanging when trying to open the TCP port. Try changing the PluginPort.

1. Close X-Plane and xPilot
2. Open `X-Plane/Resources/plugins/xPilot/Resources/Config.json` in a text editor and change PluginPort from 53100 to something else... even 53101 will work. Save the changes.
3. Open `~/Library/Application Support/org.vatsim.xpilot/AppConfig.json` with a text editor. Change XplanePluginPort to match the new port number you specified in the plugin config file. Save the changes.
4. Open xPilot and X-Plane and see if that fixes your issue.

**Comment by donks** [comment]
Tried with multiple ports and still the same behaviour (hang). A review of the netstat command doesn't show any application running on the configured ports. Curiously, I noticed that port number in the plugin config is in quotes like it is a string. When I removed the quotes, the plugin re-adds them when starting X-Plane up again.

**Comment by k9bite** [comment]
I think I'm having the same problem. Hangs on "preparing world" when I try to load a flight. I'm on a Mac.

**Comment by donks** [comment]
I’m also on a Mac. Just tested with beta 6. Same issue.

**Comment by justinshannon** [comment]
@donks @k9bite 

Does it freeze if you load up in a default aircraft (like the C172)? 

Can you try the attached plugin version? I added additional debug logging and disables immediate TCAS control. Please try and let me know your results and upload your log.txt.

[mac_x64.zip](https://github.com/xpilot-project/xpilot/files/9720703/mac_x64.zip)

**Comment by k9bite** [comment]
Sorry, I'm a little ignorant. Where do I put those zipped files?

**Comment by k9bite** [comment]
Disregard, I found it in XP12 resources, plugins...

**Comment by donks** [comment]
[Log.txt](https://github.com/xpilot-project/xpilot/files/9721592/Log.txt)

New plugin added and log file attached.

**Comment by justinshannon** [comment]
@k9bite I need your X-Plane log, not the installer log.

**Comment by k9bite** [comment]
Sorry Justin, I'm ignorant bout this stuff. What is the log called, I can't
find any other log inside XP12 folder?

**Comment by k9bite** [comment]
That worked!!!!!!  Woohoo!

Here's the log:

**Comment by justinshannon** [comment]
@donks or @k9bite

Did either of you previously use X-Plane 11 (or still have it installed)? If so, did you encounter an issue with X-Plane 11 freezing like you do with X-Plane 12?

**Comment by k9bite** [comment]
Yes ran Plane 11 w/ XPilot and did not have issues with either freezing.

**Comment by justinshannon** [comment]
@k9bite can you provide your X-Plane 12 log.txt? It doesn't look like it got attached to your previous comment.

**Comment by donks** [comment]
> @donks or @k9bite
> 
> Did either of you previously use X-Plane 11 (or still have it installed)? If so, did you encounter an issue with X-Plane 11 freezing like you do with X-Plane 12?

I have X-Plane 11 and xpilot worked fine. 
Earlier X-Plane 12 betas worked fine as well

**Comment by k9bite** [comment]
Where is the X-Plane log? When you asked last week I guess I sent you the installer log instead. I couldn’t find log.text, where is it?

**Comment by donks** [comment]
> Where is the X-Plane log? When you asked last week I guess I sent you the installer log instead. I couldn’t find log.text, where is it?
> […](#)

It’s called log.txt and is located in you X Plane 12 directory. Possibly /Applications/X-Plane 12/ depending upon where you installed it.

**Comment by k9bite** [comment]
Okay, I found it. Is actually called log.txt, I was searching for log.text, that’s why I didn’t find it before. I should have realized, since it is a text file.

**Comment by justinshannon** [comment]
No problem. I still don’t see it attached. You may need to attach it manually through the xPilot GitHub issue webpage, instead of attaching it via email.

**Comment by k9bite** [comment]
I think I forgot to attach it before

**Comment by donks** [comment]
@justinshannon - I've upgraded to beta 7 and xpilot is no longer hanging X-Plane. 
I've not made any other changes other than the X-Plane upgrade!

**Comment by k9bite** [comment]
Thank you so much. I appreciate all your hard work. I fly for Walker VA and someone on their Discord channel was talking about how great you are.

Thanks again for all you do.

Todd

**Comment by justinshannon** [comment]
> @justinshannon - I've upgraded to beta 7 and xpilot is no longer hanging X-Plane. I've not made any other changes other than the X-Plane upgrade!

Just to confirm, you're using the stock xPilot plugin and _not_ the modified version?

**Comment by k9bite** [comment]
Uh, oh. No, I’ve been using the modified version since you sent it to me last week.

**Comment by justinshannon** [comment]
Can you try again with the stock version (just re-run the xPilot installer)? The modified version disables automatic TCAS activation, which is what is causing X-Plane to freeze.

**Comment by donks** [comment]
> > @justinshannon - I've upgraded to beta 7 and xpilot is no longer hanging X-Plane. I've not made any other changes other than the X-Plane upgrade!
> 
> Just to confirm, you're using the stock xPilot plugin and _not_ the modified version?

I tried both. There is a slight hang of only a few seconds (colour wheel shown) when switching TCAS modes.
[Log.txt](https://github.com/xpilot-project/xpilot/files/9769276/Log.txt)

**Comment by k9bite** [comment]
Bad news. I uninstalled and removed all XPilot (modified) from my computer. I updated to XP12 b7, then downloaded/installed original XPilot from Github. Still hanging on Preparing World when I try to start a flight. Tried it in the C72. Log’s attached.

**Comment by justinshannon** [comment]
@k9bite sorry, I still don’t see the log. Try attaching it using the GitHub website instead of via email: https://github.com/xpilot-project/xpilot/issues/123

**Comment by k9bite** [comment]
Okay. I attached it to comment "XP12 beta 7 still hanging on Preparing World when loading flight” under Issues tab.

**Comment by donks** [comment]
> > > @justinshannon - I've upgraded to beta 7 and xpilot is no longer hanging X-Plane. I've not made any other changes other than the X-Plane upgrade!
> > 
> > 
> > Just to confirm, you're using the stock xPilot plugin and _not_ the modified version?
> 
> I tried both. There is a slight hang of only a few seconds (colour wheel shown) when switching TCAS modes. [Log.txt](https://github.com/xpilot-project/xpilot/files/9769276/Log.txt)

I think the information above was not correct as the plugin was not fully loaded due to being blocked by the macOS gatekeeper. I've put the stock plugin and application back and enabled the security with the new beta (8) and it's still hanging on preparing world. Apologies for the confusion.

**Comment by justinshannon** [comment]
The developer of XPMP2 (the library that xPilot uses to render other aircraft) has opened a bug report with Laminar.

In the meantime, you can disable TCAS integration by setting `DisableTcas` to `true` in the plugin configuration file (Config.json). This can be found in `X-Plane/Resources/plugins/xPilot/Resources`. X-Plane **must** be closed before you update the configuration file. Open this file with a text editor and save your changes.

**Comment by justinshannon** [comment]
@donks @k9bite
I’ve heard rumors that this issue is fixed in XP beta 12. Can anyone confirm this?

**Comment by donks** [comment]
Yes -  I have tested the latest release with beta 12 and no longer have a hang. Was also able to pass TCAS control between LiveTraffic without issue as well. Thanks

**Comment by justinshannon** [comment]
Thanks for confirming. I'm closing this issue.

**Comment by k9bite** [comment]
Worked for me too
