### ISSUE TITLE
Invalid Frequency Shown For Controller With Frequency Set (100.000)

### ISSUE THREAD

**Issue by StevePirateX** [xpilot-project/xpilot#125]
Not sure what is going on, but the controller did initially have their frequency but now showing 100.000
See attached image - controller in question is ML-SNO_CTR. Even when jumping on freq to the controller (which the audio works), it is still showing 100.000. The freq for the controller is 123.75.

![xpilot_bug](https://user-images.githubusercontent.com/71484299/194846226-7a63765f-cefe-4013-9b2e-d999bd5a470d.jpg)

**Comment by justinshannon** [comment]
Can you upload the relevant NetworkLog from this session, if you still have it? xPilot only keeps the last 10 logs.

* Windows: `C:/Users/<YOUR_USERNAME>/AppData/Local/org.vatsim.xpilot/NetworkLogs/`
* macOS: `~/Library/Application Support/org.vatsim.xpilot/NetworkLogs/`
* Linux: `~/.local/share/org.vatsim.xpilot/NetworkLogs/` (you might have to enable hidden files/folders to see the `.local` folder)

**Comment by StevePirateX** [comment]
Files had to be split in two (25MB file limit). A controller called Alex was online when I noticed this (as at the start Matt was online).

[NetworkLog-20221010-085250_B.txt](https://github.com/xpilot-project/xpilot/files/9748530/NetworkLog-20221010-085250_B.txt)
[NetworkLog-20221010-085250_A.txt](https://github.com/xpilot-project/xpilot/files/9748528/NetworkLog-20221010-085250_A.txt)

**Comment by StevePirateX** [comment]
It happened today as well. It started out alright but could it have anything to do with where their visibility point is set or where the AFV radio transmitters are?
