### ISSUE TITLE
Xpilot Window Completely Blank

### ISSUE THREAD

**Issue by planedude63** [xpilot-project/xpilot#126]
Hello! My xpilot window is completely blank. It shows up on taskbar, but is just blank. Its been like this for WEEKS. I've tried reinstalling it, restarting it, etc. I even went to re-coding the orientation of the app, as seen on a previous issue. Please help me!

https://user-images.githubusercontent.com/110436838/195196652-919e2fa0-4b16-4484-bc73-1f428ff3ff69.mp4

**Comment by justinshannon** [comment]
Another user had success running xPilot in compatibility mode for Vista. Right click on the xPilot application, choose properties and under the Compatibility tab check the "Run this program in compatibility mode for..." and choose Vista. You could also try one of the other options in the compatibility list as well.
