### ISSUE TITLE
XP12 beta 7 still hanging on Preparing World when loading flight

### ISSUE THREAD

**Issue by k9bite** [xpilot-project/xpilot#127]
[Log.pdf](https://github.com/xpilot-project/xpilot/files/9777924/Log.pdf)

**Comment by k9bite** [comment]
Hi Justin,

I'm seeing the issue was "completed" but I'm still having the "hang"
problem with a fresh install of XPilot for XP12. Am I missing something?

**Comment by justinshannon** [comment]
Sorry I forgot to attach my comment when I closed this. I'm closing this to remove it from the issue list. I just needed it for the log.

**Comment by k9bite** [comment]
Cool. I just thought I was missing something or doing something wrong that was causing the problem.
