### ISSUE TITLE
Beta36: XP11 Linux - Plugin fails to load dlerror:libfmod.so.13:

### ISSUE THREAD

**Issue by argonius-ch** [xpilot-project/xpilot#128]
The XP11 plugin does not load: dlerror:libfmod.so.13: cannot open shared object file: No such file or directory -- full XP Log.txt attached

Running ldd gives the following output (Ubuntu 22.04):
	linux-vdso.so.1 (0x00007ffe38564000)
	libfmod.so.13 => not found
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f68d0550000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f68d0469000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f68d0449000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f68d0444000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f68d021a000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f68d0b7e000)

libfmod.so is located in the plugin directory. 

[Log.txt](https://github.com/xpilot-project/xpilot/files/9844190/Log.txt)

**Comment by justinshannon** [comment]
@argonius-ch can you try this version? https://github.com/xpilot-project/xpilot/suites/8909988497/artifacts/408036074

**Comment by argonius-ch** [comment]
works - plugin loads in XP11 and XP12

**Comment by gordboy** [comment]
Confirmed working here too for XP11, but menu icon is missing.

Expected ~/xPilot/xpilot.png - but file is missing. Otherwise seems OK thus far.

**Comment by gordboy** [comment]
I spoke too soon see https://github.com/xpilot-project/xpilot/issues/131
