### ISSUE TITLE
Cannot browse to xplane12 folder on Linux

### ISSUE THREAD

**Issue by hoover67** [xpilot-project/xpilot#129]
Trying to install the CSL files (download works), I see the following message when trying to browse the xplane12 folder: 

hoover@dirac:~/xPilot$ ./xPilot.AppImage 
qrc:/Resources/Components/DownloadCSLModels/SetXplanePath.qml:62:9: QML FolderDialog: Failed to load non-native FolderDialog implementation:
qrc:/qt-project.org/imports/QtQuick/Dialogs/quickimpl/qml/FolderDialog.qml:40 module "Qt.labs.folderlistmodel" is not installed

I downloaded the latest appimage. 

v 2.2.0 beta 36. 

Cheers, 

Uwe

**Comment by gordboy** [comment]
@hoover67

Looks to me like you have made a typo. If that is exactly what you typed, then it is wrong.

Your xPilot directory is `~/xPilot`

and your AppImage is at `~/xPilot/xPilot.AppImage`

you have an extra $ and a space in the path ...

If you are in your home directory, then you can launch with `./xPilot/xPilot.AppImage`

there should be no $ signs or unescaped spaces ...

**Comment by hoover67** [comment]
xpilot launches fine, I just pasted the entire terminal content above, sorry for the confusion. 

As you can tell from the bash prompt, my working directory is /home/hoover/xPilot (the home part abbreviated to ~ as per  Unix custom :-)) 

Thanks for your reply! 

Uwe

**Comment by justinshannon** [comment]
@hoover67 what distro/version of Linux?

**Comment by hoover67** [comment]
It's Linux Mint 20 Cinnamon Edition. 

Is there a way to manually install the CSL files? I've already done so for swift which I've also been testing. Also, where does xpilot store the downloaded CSL file? When I restart xpilot, it apparently picks up the download and directly offers to install the library again without having to re-download it. 

For swift, I installed the CSL files here: 

hoover@dirac:~/xplane12$ ls -l Custom\ Data/CSL/
total 4
drwxrwxr-x  2 hoover hoover    6 Oct 16 10:48 BB
drwxrwxr-x 15 hoover hoover  205 Oct 16 10:49 BB_Airbus
drwxrwxr-x  6 hoover hoover   83 Dec 15  2020 BB_Air_Spain_VA
drwxrwxr-x  2 hoover hoover 4096 Dec 15  2020 BB_Alpaca_VA
drwxrwxr-x 17 hoover hoover  229 Oct 16 10:49 BB_Boeing
drwxrwxr-x  5 hoover hoover   71 Dec 18  2021 BB_Compass_VA
drwxrwxr-x  6 hoover hoover   78 Dec 18  2021 BB_FlyItaly_VA
drwxrwxr-x  8 hoover hoover  121 Nov 11  2018 BB_GA
drwxrwxr-x  4 hoover hoover   58 Jul 27  2021 BB_German_Air_Express_VA
drwxrwxr-x  5 hoover hoover   83 Nov 11  2018 BB_Heli
drwxrwxr-x 22 hoover hoover  287 Nov 11  2018 BB_Jets
drwxrwxr-x  6 hoover hoover   83 Dec 15  2020 BB_Leipzig_Air_VA
drwxrwxr-x 22 hoover hoover  283 Nov 11  2018 BB_Mil
drwxrwxr-x  8 hoover hoover  105 Feb  5  2021 BB_Pacific_Airways_VA
drwxrwxr-x 11 hoover hoover  156 Dec 14  2020 BB_Props
drwxrwxr-x  6 hoover hoover   86 Aug 15  2021 BB_RegioAir_VA
drwxrwxr-x 18 hoover hoover  241 Dec 18  2021 BB_Repaints
drwxrwxr-x  4 hoover hoover   58 Dec 16  2020 BB_Roma_Airways_VA
drwxrwxr-x  4 hoover hoover   58 Dec 15  2020 BB_Simwings_VA
drwxrwxr-x  7 hoover hoover   93 Jul 10  2021 BB_SUR_Air_VA
drwxrwxr-x  7 hoover hoover   93 Aug 16  2021 BB_WAT_VA

All the best, 

Uwe

**Comment by justinshannon** [comment]
Yes, you can manually configure the path to your CSL models: https://beta.xpilot-project.org/#/xplane?id=csl-configuration

**Comment by justinshannon** [comment]
Give this version a try: https://github.com/xpilot-project/xpilot/suites/8917052070/artifacts/408629301
