### ISSUE TITLE
Minimum horizontal Window Size: 800 pixels needed

### ISSUE THREAD

**Issue by retostockli** [xpilot-project/xpilot#130]
The minimum horizontal window size for xPilot on Linux / X11 is currently 909 pixels. I cannot narrow the window more. I am however running xPilot on a external monitor in landscape mode and would like to set the window size to 800 pixels. The header row boxes (CONNECT, MODE C, IDENT, FLIGHT PLAN and SETTINGS) should fit well also with 800 pixels.

Would you mind adapt the minimum horizontal windows size to 800 pixels?
Cheers,
Reto

**Comment by justinshannon** [comment]
The smallest window width will be 840px. This is to ensure that the connected callsign can fit in the toolbar area.

This change will be available in a future update.

**Comment by retostockli** [comment]
Thanks! 840 should somehow work :-)
I'll test.
