### ISSUE TITLE
Beta36 Linux receives but cannot send

### ISSUE THREAD

**Issue by gordboy** [xpilot-project/xpilot#131]
PTT and text in the client app both give network error on send, receive is OK.

Liking 36 a lot better than 35 apart from that small defect ...

Using beta 36 with FMOD fix from
https://github.com/xpilot-project/xpilot/suites/8909988497/artifacts/408036074

**Comment by justinshannon** [comment]
Can you upload the respective network log? It can be found in `~/.local/share/org.vatsim.xpilot`

A screenshot of said error would also be helpful. 

What distro/version of Linux?

**Comment by gordboy** [comment]
OK will do. At work just now. Back later.

**Comment by gordboy** [comment]
Looks like a false alarm Could be old settings from a previous version.

Created a new user, a new plugins folder &etc and all is now well, apart from the missing app icon as I mentioned somewhere previously.

Will now close this issue. Thanks for your great response times and service.
