### ISSUE TITLE
XPilot displays issue traffic position during takeoff and landing

### ISSUE THREAD

**Issue by AntonKuf** [xpilot-project/xpilot#132]
From XPilot version 0.36 or or late, during landing, traffic levels off at a height of approximately 100 feet and then plummets. during takeoff, traffic rises sharply to a height of about 100ft and then continues a smooth climb. 
https://youtu.be/HfNFZ-y1EkQ

**Comment by AntonKuf** [comment]
> Which version of X-Plane?

XPlane12.00b9

**Comment by AntonKuf** [comment]
Hello! I tested the new version of the pilot and the problem remained. Jumps occur during takeoff and landing. During landing it looks like the glide slope profile is shifted higher. https://youtu.be/7Orc0E0zqIw

**Comment by AntonKuf** [comment]
Could you remove the height offset for now? Or make a choice.

**Comment by justinshannon** [comment]
It should be fixed in the next release, which I'll try to get published this weekend sometime.

**Comment by AntonKuf** [comment]
> It should be fixed in the next release, which I'll try to get published this weekend sometime.

Is there an estimated release time? Thank you!

**Comment by justinshannon** [comment]
This should be fixed in beta 39 (just released).
