### ISSUE TITLE
[Bug] R37 Faulty Mic Connection

### ISSUE THREAD

**Issue by ml0130** [xpilot-project/xpilot#134]
It seems like there might be a current bug in the current release that's causing microphones to bug out and xpilot to stop picking up any sound the mic would be picking up. Currently, a temp fix I have found is to change between mic sources. But there no telling how long it lasts.

**Comment by justinshannon** [comment]
One other user has reported this as well; they were able to even reproduce it by leaving the Settings window open and watching for the microphone calibration indicator to stop responding (which happens after about 10 minutes for them). 

Can you perform a similar test with the xPilot Settings window? When you do this, can you also watch your overall CPU utilization (in task manager) to see if maybe your CPU is bottlenecking, thus causing issues with xPilot audio processing?

**Comment by justinshannon** [comment]
Beta 38 should resolve this issue. If the problem persists after upgrading, please open a new issue.
