### ISSUE TITLE
BETA 38 - Freezes Xplane 11

### ISSUE THREAD

**Issue by vinzane21** [xpilot-project/xpilot#136]
Hello. I would just like to report that everytime I uses xpilot, it freezes my flight sim which is Xplane 11. After it freezes, it will then disconnect. It says something like lost connection.

I have attached my log. I think its about the TCAS something im not sure.
[Log.txt](https://github.com/xpilot-project/xpilot/files/9996525/Log.txt)

**Comment by vinzane21** [comment]
I have a screenshot of my xpilot
![Untitled](https://user-images.githubusercontent.com/118093528/201516605-ad78502b-3e0f-4324-875b-a3ed11c2ab40.png)

**Comment by jonaseberle** [comment]
Can you add a bit more context what you did in that Log.txt session?

It seems you made a successful flight. After that X-Plane freezed?
What did you do when it happened? Do you mean by "everytime I uses xpilot" you opened xPilot?
Is it reproducible when you do the same thing?

**Comment by vinzane21** [comment]
ok.. so i was just sitting on the ground on that log.tx ive sent.
Im just planning my flight. adding the waypoints in the mcdu and looking the views around and suddenly xplane freezes. but it will come back to normal when i click xpilot back. i mean not in minimize mode. but if ill minimize the xpilot again. after a couple of mins. xplane will freeze again

**Comment by vinzane21** [comment]
![not responding](https://user-images.githubusercontent.com/118093528/201523630-8028d77b-87c2-48d0-a1f8-34acd8637b7f.png)
suddenly not responding. :( it comes back to normal when i click back the xpilot

**Comment by vinzane21** [comment]
UPDATE: It reduces the occurrence of "Npt Responding" state when I've tried to run Xpilot to a compatibility mode to Windows Vista Service Pack 2. but it still happen but less now. I just have to click the xpilot so it would stay front in my screen and to stop the "Not Responding" state.

**Comment by justinshannon** [comment]
Can you try adding xPilot.exe to the Windows Defender exclusion list?

![WindowsDefenderExclusion](https://user-images.githubusercontent.com/3221191/201536561-19c6a3f1-3def-4014-8c69-286d71231231.gif)

**Comment by vinzane21** [comment]
> Can you try adding xPilot.exe to the Windows Defender exclusion list?
> 
> ![WindowsDefenderExclusion](https://user-images.githubusercontent.com/3221191/201536561-19c6a3f1-3def-4014-8c69-286d71231231.gif) [ ![WindowsDefenderExclusion](https://user-images.githubusercontent.com/3221191/201536561-19c6a3f1-3def-4014-8c69-286d71231231.gif) ](https://user-images.githubusercontent.com/3221191/201536561-19c6a3f1-3def-4014-8c69-286d71231231.gif) [ ](https://user-images.githubusercontent.com/3221191/201536561-19c6a3f1-3def-4014-8c69-286d71231231.gif)

Thank you for the suggestion. Ok ive followed your instructions. still the same. :( i have attached the log file. but it seems theres nothing we can see in the log.

I just run it in compatibility mode.
[Log.txt](https://github.com/xpilot-project/xpilot/files/10001528/Log.txt)

**Comment by vinzane21** [comment]
update : no luck. it could be my system that has some problems? it is the same with swift too. ive just tried to test if its xpilot problem. do you recommend to run the programs as admin?

**Comment by jonaseberle** [comment]
Have you tried without all your other plugins? That should be the first step IMHO if you have any problems in X-Plane.

**Comment by justinshannon** [comment]
Your best bet would be to submit a support ticket with Laminar. Your issue is outside the scope of xPilot support, sorry.
