### ISSUE TITLE
Feature request: Linux: Add .zip with app+plugin to releases

### ISSUE THREAD

**Issue by jonaseberle** [xpilot-project/xpilot#138]
For some use cases it is more convenient to have a direct download of the plugin and the app instead of the installer.

I can only talk about Linux, but maybe this is useful for other OSes as well.

On modern Linux, AppImages are managed by [appimaged](https://github.com/probonopd/go-appimage), taking care of menu entry creation. When running a `.AppImage`, the desktop integration will ask if it should move it to the user's AppImage-location. This the installer is adding a superfluous and potentially confusing step.
Having direct downloads at Github releases would also allow the download to be scripted, easing maintenance if you have a networked setup and/or multiple X-Plane instances.

Could we have the app and plugins as direct downloads at [the releases](https://github.com/xpilot-project/xpilot/releases/tag/v2.0.0-beta.38)?

**Comment by justinshannon** [comment]
Starting with beta 39, a new artifact archive package will be available with each release. The archive contains the xPilot executable and plugin files for each OS, so you'll have to pick out the files you specifically want.
