### ISSUE TITLE
Mac Ventura

### ISSUE THREAD

**Issue by sgljungholm** [xpilot-project/xpilot#140]
Just updated my Mac system to Ventura and now I can't get this to launch, it asks for Mic access and then seems to stall. 
Just got this all working a few days ago and now I am stuck. Love the app so far...

**Comment by sgljungholm** [comment]
But no mic access, had to roll back to .38. It asks for permission but no audio received,

**Comment by justinshannon** [comment]
This issue is fixed in beta 40.
