### ISSUE TITLE
XPilot disconnecting non-stop.

### ISSUE THREAD

**Issue by FarisArch** [xpilot-project/xpilot#141]
Hi team.

I've been using XPilot for months now but I've encountered this issue that happened I'd say 2-3 days ago. I've been getting disconnected with the error **Voice server error :Timeout** and getting reconnected back. See picture below : 

![Capture](https://user-images.githubusercontent.com/74707793/210174831-2abb8595-d7e7-49de-9497-808f0234b2a7.PNG)

I'm not sure where and how to troubleshoot this issue. Attached is also my log.txt

[Log.txt](https://github.com/xpilot-project/xpilot/files/10328946/Log.txt)

Thanks for your hard work.

**Comment by FarisArch** [comment]
Seems like it's the same issue as #73 
Weird that I'm getting connection issues after so long being fine.

**Comment by justinshannon** [comment]
As mentioned in #73, this is an issue with your internet connection and the voice server.
