### ISSUE TITLE
External audio supplied by xPilot vBeta 41

### ISSUE THREAD

**Issue by gkkes** [xpilot-project/xpilot#142]
On starting xPilot I hear all other Vatsim members aircraft characteristics as if I'm outside the cockpit.
There is no control of these exterior sounds in the X-Plane 12 Settings Sound mixer.

**Comment by justinshannon** [comment]
You can enable/disable or adjust the volume of the aircraft sounds in the xPilot plugin settings: https://beta.xpilot-project.org/#/xplane?id=settings
