### ISSUE TITLE
XPlane 12 on Linux crashes with XPilot installed

### ISSUE THREAD

**Issue by Jarlath-tg** [xpilot-project/xpilot#143]
XPilot for Linux crashes XPlane app in two situations:
1. On XPlane exit
2. On XPilot plugin disable action in Plugin Admin (log attached)  
[Log.txt](https://github.com/xpilot-project/xpilot/files/10367977/Log.txt)

When crash: screen freeze, sound from xplane stay, plugin disconnects with XPilot app (X-Plane connection lost.)

Tested with another plugins and with XPilot as the only plugin installed.

Issue on:
XPlane 12.00r6
XPilot  2.0.0-b.41 and 2.0.0-b.42

**Comment by justinshannon** [comment]
What distro of Linux?

**Comment by Jarlath-tg** [comment]
Hi,
       Gentoo Linux, KDE as desktop environment. I'm new with XPilot (earlier use Swift Pilot app), so I have no experience with previous versions.

**Comment by justinshannon** [comment]
I don't have a Linux machine that I can test this on (X-Plane doesn't run on a VM). The log file you attached doesn't show any sort of crash message. My Linux knowledge is pretty limited; however, are you able to obtain some sort of debug crash report using GDB?

**Comment by jonaseberle** [comment]
@Jarlath-tg do you use pipewire? 
In that case I had a similar problem which could be worked around: https://github.com/xpilot-project/xpilot/issues/137

**Comment by Jarlath-tg** [comment]
@justinshannon not a gdb specialist, but:

`#0  0x00007f4ff74b4287 in  () at /lib64/libc.so.6
#1  0x00007f4ff74bf1b8 in  () at /lib64/libc.so.6
#2  0x00007f4ff73bac86 in  () at /home/jarlath/.mnt/Vol1/SteamApps/common/X-Plane 12/Resources/dlls/64/libfmod.so.13
#3  0x00007f4ff72ed283 in  () at /home/jarlath/.mnt/Vol1/SteamApps/common/X-Plane 12/Resources/dlls/64/libfmod.so.13
#4  0x00007f4ff738bf3c in  () at /home/jarlath/.mnt/Vol1/SteamApps/common/X-Plane 12/Resources/dlls/64/libfmod.so.13
#5  0x00007f4ff7310e0b in  () at /home/jarlath/.mnt/Vol1/SteamApps/common/X-Plane 12/Resources/dlls/64/libfmod.so.13
#6  0x00007f4ff73123e7 in  () at /home/jarlath/.mnt/Vol1/SteamApps/common/X-Plane 12/Resources/dlls/64/libfmod.so.13
#7  0x00007f4ff72ef17b in FMOD::System::release() () at /home/jarlath/.mnt/Vol1/SteamApps/common/X-Plane 12/Resources/dlls/64/libfmod.so.13
#8  0x00007f4ef74628c9 in XPMP2::SoundCleanup() () at /home/jarlath/.mnt/Vol1/SteamApps/common/X-Plane 12/Resources/plugins/xPilot/lin_x64/xPilot.xpl
#9  0x00007f4ef745b57b in XPMPMultiplayerCleanup () at /home/jarlath/.mnt/Vol1/SteamApps/common/X-Plane 12/Resources/plugins/xPilot/lin_x64/xPilot.xpl
#10 0x00007f4ef73425b0 in XPluginDisable () at /home/jarlath/.mnt/Vol1/SteamApps/common/X-Plane 12/Resources/plugins/xPilot/lin_x64/xPilot.xpl
#11 0x00007f4f7c102544 in XPLMDisablePlugin () at /home/jarlath/.mnt/Vol1/SteamApps/common/X-Plane 12/Resources/plugins/XPLM_64.so
#12 0x00007f4f7c102497 in XPLMDisableAllPlugins() () at /home/jarlath/.mnt/Vol1/SteamApps/common/X-Plane 12/Resources/plugins/XPLM_64.so
#13 0x00007f4f7c0fe7d6 in XPLMShutdownPlugins () at /home/jarlath/.mnt/Vol1/SteamApps/common/X-Plane 12/Resources/plugins/XPLM_64.so
#14 0x000000000173c9b0 in XPPShutdownPlugins() ()
#15 0x000000000193b901 in MACIBM_finishup(int) ()
#16 0x000000000193b6b6 in main ()
`

**Comment by Jarlath-tg** [comment]
@jonaseberle Thank you, Yes I have enabled pipewire by default in my system.

**Comment by Jarlath-tg** [comment]
@jonaseberle 
Confirmed:
sudo ln -s /bin/true /bin/pulseaudio
Solves the issue for me. 
Thx
