### ISSUE TITLE
Immediate core dump of xPilot v2.0.0-beta.42

### ISSUE THREAD

**Issue by cohomology** [xpilot-project/xpilot#146]
After installing xPilot v2.0.0-beta.42 on Linux with xplane 12, I get an immediate core dump / segmentation fault when starting xPilot.

Call stack is:

0x0000555555932a08 in ma_context_get_device_info_source_callback__pulse(ma_pa_context*, ma_pa_source_info const*, int, void*) ()
(gdb) where
#0  0x0000555555932a08 in ma_context_get_device_info_source_callback__pulse(ma_pa_context*, ma_pa_source_info const*, int, void*) ()
#1  0x00007ffff410da46 in  () at /lib/x86_64-linux-gnu/libpulse.so
#2  0x00007fffeef8b383 in  ()
    at /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-15.99.so
#3  0x00007fffeef8c5bf in pa_pdispatch_run ()
    at /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-15.99.so
#4  0x00007ffff4101083 in  () at /lib/x86_64-linux-gnu/libpulse.so
#5  0x00007fffeef91487 in  ()
    at /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-15.99.so
#6  0x00007fffeef921d8 in  ()
    at /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-15.99.so
#7  0x00007fffeef9259a in  ()
    at /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-15.99.so
#8  0x00007fffeef9673a in  ()
    at /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-15.99.so
#9  0x00007ffff4114a73 in pa_mainloop_dispatch () at /lib/x86_64-linux-gnu/libpulse.so
#10 0x00007ffff41150ca in pa_mainloop_iterate () at /lib/x86_64-linux-gnu/libpulse.so
#11 0x0000555555932670 in ma_context_get_device_info__pulse(ma_context*, ma_device_type, ma_device_id const*, ma_device_info*) ()
#12 0x0000555555933dc0 in ma_context_get_device_info ()
#13 0x000055555594dbfd in afv_native::audio::MiniAudioAudioDevice::getCompatibleOutputDevices() ()
--Type <RET> for more, q to quit, c to continue without paging--
#14 0x000055555594e857 in afv_native::audio::AudioDevice::getCompatibleOutputDevicesForApi(unsigned int) ()
#15 0x0000555555894104 in xpilot::AudioForVatsim::configureAudioDevices() ()
#16 0x0000555555896fdf in xpilot::AudioForVatsim::AudioForVatsim(QObject*) ()
#17 0x000055555588c698 in xpilot::Main(int, char**) ()

**Comment by justinshannon** [comment]
Known issue, will be fixed in the next release. https://github.com/xpilot-project/xpilot/issues/145
