### ISSUE TITLE
Contrails

### ISSUE THREAD

**Issue by boriskaXP** [xpilot-project/xpilot#148]
Sometimes xpilot doesn't draw contrails
![image](https://user-images.githubusercontent.com/49883379/216791214-d2637f98-c9c0-4344-985f-9698afb8d38d.png)

**Comment by justinshannon** [comment]
You’ll need to provide more context, such as what altitude this aircraft was at.

**Comment by boriskaXP** [comment]
It was on FL350

**Comment by justinshannon** [comment]
I'm going to close this out as a fluke; it's really hard to investigate this further without any sort of logs. If it happens again, feel free to reopen this issue and include the altitude of the aircraft and how far away they were from you.
