### ISSUE TITLE
Revert to version v2.0.0-beta.43

### ISSUE THREAD

**Issue by githubvatsim** [xpilot-project/xpilot#154]
The recent xpilot update for XP11 on the Mac rendered the Colimata Concorde autopilot unusable. Reverting to beta-43 resolved the problem.

**Comment by justinshannon** [comment]
Can you be more specific? xPilot doesn't not touch anything related to autopilot, so I'm confused how it's rendering it "unusable". What exactly breaks when you use the latest xPilot version with said aircraft?

**Comment by githubvatsim** [comment]
The Concorde autopilot won’t fly set airspeed, rate of climb or level off at a target altitude. On the Concorde forum there have been other occasions when plugin conflicts have caused problems and this seem to be one. I can only say that reverting to the previous xPilot version resolved it.

**Comment by justinshannon** [comment]
Like I said, xPilot does not touch any autopilot controls of aircraft, so I don't know why you would experience such issues when using xPilot. There's not much I can do about this, sorry.

**Comment by githubvatsim** [comment]
This problem resolves if XP11 is launched before xPilot.
