### ISSUE TITLE
Linux installer cannot be resized on Fedora 37 KDE wayland

### ISSUE THREAD

**Issue by MTRNord** [xpilot-project/xpilot#155]
Hi I am having the issue that the installer itself works however since the window is not resizable I cannot select the xplane location. Is there any known workaround?

![image](https://user-images.githubusercontent.com/1374914/224553948-561d535c-be98-42d3-907f-e306cc1ec9f9.png)

**Comment by justinshannon** [comment]
I’m not sure if there is a workaround or not. The installer wizard is a third-party tool, and I don’t see anything in the documentation about allowing the window to be resized.

Are you able to (temporarily) reduce the window scaling in your OS settings?

**Comment by MTRNord** [comment]
I dont think there is a way to reduce the scaling. However I found that there is a `--mode text` flag that can be used to just do the whole install from the console which seems to work. I guess this is an acceptable workaround. :)

**Comment by justinshannon** [comment]
That’s good to know, thanks!
