### ISSUE TITLE
Update hangs indefinitely

### ISSUE THREAD

**Issue by manymiles** [xpilot-project/xpilot#156]
When prompted that a new version is available, and following through on the download and install, the update never fully starts.  It gets stuck on "Waiting for xPilot to exit", when there is no visual indication that xPilot is running.

A `ps` check indicates the main app did not close.  A `killall` allows the update to proceed.

However, after proceeding, the updating program crashes.

NB: The updating app completes properly when downloading and starting as a standalone app.

See attached.
![Screenshot from 2023-03-16 08-02-08](https://user-images.githubusercontent.com/32308485/225615627-cd34afd9-a6b8-4252-9d5e-c2071096be7f.png)
[Screencast from 03-16-2023 08:03:41 AM.webm](https://user-images.githubusercontent.com/32308485/225615652-d5be57f7-4e37-4658-81d1-3c727a972885.webm)

**Comment by manymiles** [comment]
I should have included...

This is an Ubuntu 22.04. It has been this way for many beta versions, I just haven't reported it prior to now. It wasn't ALWAYS this way, but, I can't remember when it did start.

**Comment by manymiles** [comment]
I can report that it also happens when I'm booted into Windows on the same hardware.

**Comment by justinshannon** [comment]
This should be fixed in the next release (f73d5b0).

**Comment by justinshannon** [comment]
This should be fixed in the latest version.
