### ISSUE TITLE
Setup app text difficult/impossible to read

### ISSUE THREAD

**Issue by manymiles** [xpilot-project/xpilot#157]
The colors/font/something(?) makes the Setup program very difficult if not impossible to read.

This is an Ubuntu 22.04.  The setup program is `xPilot-2.0.0-beta.48-Linux.run`.  It is started from a BASH shell.  It has been this way for many beta versions, I just haven't reported it prior to now.  It wasn't ALWAYS this way, but, I can't remember when it did start.

By the way, I LOVE xPilot.  Thanks so much for creating and maintaining it.

![Screenshot from 2023-03-16 08-03-12](https://user-images.githubusercontent.com/32308485/225616348-8eace27a-fce8-4515-a29b-aaa7b83307ce.png)

**Comment by justinshannon** [comment]
This will be fixed in the next release (2e9e023).

**Comment by justinshannon** [comment]
This should be fixed in the latest version.
