### ISSUE TITLE
Airplane volume control not working

### ISSUE THREAD

**Issue by AntonKuf** [xpilot-project/xpilot#162]
I noticed that the volume control now does not work on the plane.
![11223](https://user-images.githubusercontent.com/70604383/229520143-97d0ac30-b29e-4381-a670-3f8221c04d65.png)

**Comment by jonaseberle** [comment]
That looks like a Toliss bus. That has worked for me.
Yes, the sliders in the settings are not updating but the volume control from the cockpit adjusts the volume. Doesn't it do that for you?

**Comment by justinshannon** [comment]
https://beta.xpilot-project.org/#/client?id=audio-devices

> You can also adjust the COM1 and COM2 volumes here. Alternatively, you can adjust the COM1 and COM2 volumes via the volume knobs in the aircraft radio panel. **Note: The volume sliders in the xPilot settings do not reflect adjustments made via the aircraft radio stack volume knobs, and vice versa.** So, if you adjust the radio volumes inside the aircraft, the volume sliders will not reflect this change; when you restart xPilot, the volumes will revert to the previous volume levels as set by the volume sliders.

**Comment by AntonKuf** [comment]
Yes, you are right, it works. I'm sorry)
