### ISSUE TITLE
[Feature Request] Separate COM1 and COM2 Outputs

### ISSUE THREAD

**Issue by retostockli** [xpilot-project/xpilot#164]
I am running a B737 simulator and can assign different headsets to different COM radios. Unfortunately, COM1 and 2 are currently mixed into a single audio device.
Would you mind thinking about adding the following options:
a) Include a user setting to send COM1 via the left and COM2 via the right audio channel of that device (so users can separate those signals externally).
b) Include a feature to assign COM1 to audio device X and COM2 to audio device Y.

I would prefer option a) since it only requires a single audio device for both COM radios. What do you think?

**Comment by justinshannon** [comment]
Option A has been implemented in the next version. I plan on releasing it sometime after CTP.

**Comment by justinshannon** [comment]
This is now available in beta 50.
