### ISSUE TITLE
Radio tunes to random frequency when controller disconnects

### ISSUE THREAD

**Issue by Bevan0** [xpilot-project/xpilot#168]
This has happened to me two times so far. When the controller I'm listening to disconnects, COM1 automatically tunes to a random frequency that no controller is on without any message or anything. I'm on xPilot v2.0.0-beta.49 and newest version of XP12.

**Comment by justinshannon** [comment]
Open the X-Plane ATC window and turn off the “Auto-tune recommended frequencies” option.

**Comment by Bevan0** [comment]
I already have it off.

![Screenshot from 2023-06-17 14-27-11](https://github.com/xpilot-project/xpilot/assets/43471745/1b345213-05ec-4412-99d4-49ebd51f8eb3)

**Comment by justinshannon** [comment]
You must have something else that is auto-tuning the frequency then; xPilot does not randomly change frequencies.
