### ISSUE TITLE
X-Plane for Linux on Debian 12 Bookworm crashes upon exit when xPilot plug-in is installed

### ISSUE THREAD

**Issue by chrkrist** [xpilot-project/xpilot#169]
I have tested without the plug-in installed.. then there is no problem

Last 3 lines from log.txt in the root xplane 12 folder

0:00:29.939 I/PLG: The plugin xPilot 2.0.0-beta.49 is setting global TCAS override to 0.
The plugin xPilot 2.0.0-beta.49 is releasing control of AI aircraft.
0:00:29.939 I/PLG: The plugin xPilot 2.0.0-beta.49 is setting global TCAS override to 0.

Workoround for now is just to use 'ps aux' from terminal. Locate the PID for xplane, and kill it.

**Comment by justinshannon** [comment]
Can you try this workaround? https://github.com/xpilot-project/xpilot/issues/143#issuecomment-1376033225

**Comment by chrkrist** [comment]
I can confirm that using workaround #143 solves the problem with X-Plane 12 exit on my Debian 12 Bookworm installation.

Many thx for your help :-)
