### ISSUE TITLE
No Matter What Folder???

### ISSUE THREAD

**Issue by PortAlpha** [xpilot-project/xpilot#171]
I am a iMac 24 M1 user and when attempting to save XPilot downloaded file no matter what folder I try (yes I have tried to save in both XPlane 11 and 12 folders to include sub-folders) and each time I receive text saying file can't be saved in particular folder. I literally tried every folder and sub-folder 20 or more times on my computer to include my XPlane folders (11 and 12) and nothing works. I even turned off every security setting just to see if anything changed...nothing changed??? VATSIM download and registration went smooth just NO way to connect to use VATSIM! Please, please, help!!! Screenshot below link in quotations! 
 
Screenshot 2023-06-21 at 6 15 48 PM
https://github.com/xpilot-project/xpilot/assets/137079786/5135f680-12c3-45b1-afbc-3455e2054279

**Comment by justinshannon** [comment]
Can you provide a screenshot of the window after you select the folder? I want to see the path that gets shown in the dialog.

**Comment by PortAlpha** [comment]
Here is the actual screenshot trying to save to one of my folders. 
Allen 
￼

**Comment by justinshannon** [comment]
@PortAlpha sorry, the screenshot didn't come through. Can you try again? You may need to attach it directly through GitHub instead of via email.

**Comment by PortAlpha** [comment]
Screenshot just taken trying to save into my XP 11 folder.

If screenshot doesn’t come through this is what is says:

“ The xPilot plugin resources folder (/Users/alle.portman/Desktop/X-Plane 11/Resources/plugins/xPilot) is not readable. Verify the folder permissions and try again”

No matter what folder I try a similar messages occurs.

Allen

￼

**Comment by PortAlpha** [comment]
Here you go on screenshot. 
<img width="835" alt="Screenshot 2023-06-22 at 11 31 49 PM" src="https://github.com/xpilot-project/xpilot/assets/137079786/a137cc4d-663b-481c-855f-f9d15db4a659">

**Comment by justinshannon** [comment]
Make sure the folder `/Users/alle.portman/Desktop/X-Plane 11/Resources/plugins/xPilot` has the proper permissions.

Locate this folder in Finder and right-click on it and choose "Get Info" and make sure the Sharing & Permissions is set to "Read & Write" for your user.

![Screen Shot 2023-06-22 at 22 50 33](https://github.com/xpilot-project/xpilot/assets/3221191/6606be08-fd17-4f9e-a1be-c14b296db138)

**Comment by PortAlpha** [comment]
I had already made sure any/all these folders had read/write selected. I will keep on trying things and hope something starts working. I really appreciate your assistance!

**Comment by justinshannon** [comment]
@PortAlpha were you able to resolve this?
