### ISSUE TITLE
XPilot is open but doesn't show up

### ISSUE THREAD

**Issue by Birbsayshennlo** [xpilot-project/xpilot#180]
If I open XPilot it opens but I see nothing. I have tried lots of older versions but nothing worked.(BTW, Why are all the available versions betas?) I'm using the Beta 49 version with a 2023 MacBook pro.

**Comment by justinshannon** [comment]
Try resetting the window coordinates in the config file. Find the AppConfig.json file in `~/Library/Application Support/org.vatsim.xpilot/`. Open the file with a text editor and find the `WindowConfig` section. Change the `X` and `Y` values to `0`. Save and close the config file and try opening xPilot again.

**Comment by musabhamid** [comment]
> Try resetting the window coordinates in the config file. Find the AppConfig.json file in `~/Library/Application Support/org.vatsim.xpilot/`. Open the file with a text editor and find the `WindowConfig` section. Change the `X` and `Y` values to `0`. Save and close the config file and try opening xPilot again.

it does not work. any other way?

**Comment by musabhamid** [comment]
it says xpilot is open on macOS  but does not show up? i have the latest everything.

**Comment by justinshannon** [comment]
I’m not sure, usually resetting the config file fixes it. 

Can you try deleting the AppConfig.json file instead (you’ll have to reconfigure your network credentials and audio devices)? Make sure xPilot is closed before you do this.

**Comment by musabhamid** [comment]
I’m not sure what a config file is or any of what you just said. I searched
it up. But I get nothing. I use macOS. And it’s annoying becuase iv been
wanting to hop on the server for 3 days now. I’m in love with that game, so
it really really bugs me out that I can’t connect.

**Comment by musabhamid** [comment]
Where do I find theses files? What’s the name of the folders ?

**Comment by musabhamid** [comment]
If you help me through this I will be very happy.

**Comment by justinshannon** [comment]
See a few comments up. I provided steps on how to find (and edit) the AppConfig file, which you replied "it does not work. any other way?".

**Comment by musabhamid** [comment]
Ok, I'll take a look.
But if it stil does not
Work. Or I don’t find it?

**Comment by justinshannon** [comment]
Delete the AppConfig.json and try again. Then report back with your results.

**Comment by musabhamid** [comment]
No luck. look at the top. it says in white "Xpilot" and down under the icon
there's a dot. white dot indicating xpilot is on. but there is no window I
can access. i deleted Appconfig.json. but it was named config.json or
something like that i can't remember. still no luck. i reinstalled no luck.
don't know what now.

**Comment by musabhamid** [comment]
i cant send it. the ss is too big

**Comment by musabhamid** [comment]
<img width="1440" alt="Screenshot 2023-10-29 at 20 12 48" src="https://github.com/xpilot-project/xpilot/assets/149291417/643a1a4f-f01d-44cb-a59d-391a87a3053c">

**Comment by musabhamid** [comment]
wait nvm. how do i delte from here tho?
<img width="1440" alt="Screenshot 2023-10-29 at 20 28 07" src="https://github.com/xpilot-project/xpilot/assets/149291417/f2d5b13f-ade8-465b-a9c4-b9fd150ed007">

**Comment by musabhamid** [comment]
i only see the AppConfig.json on the website i just searched up but i cant see it on my PC or in any folders and textedit requires it to be on a folder but i cant.

**Comment by justinshannon** [comment]
1. Open Finder on your Mac, and click "Go" on the Apple menu bar.

2. Select "Go to Folder" or press the key combination "Shift + Command + G".

3. Type the path `~/Library/Application Support/org.vatsim.xpilot` in the search box and press your Return key.

**Comment by musabhamid** [comment]
BROOOO JUSTINNNN. IT WORKED. MANNNNNN THAT WAS EASY THE WAY YOU RBOKE THE
STEPS DOWNN. I UNDERSTOOD PERFECTLYY. AND IT WORKED.. BRO THANKS SOOO
MUCHHHH BRO REALLY APPRECIATE IT MANN THANKS

**Comment by musabhamid** [comment]
Ok let me chill. i was extremely happy. the way you broke it Down it steps really help me out. it wokrs perfectly like normal thanks to you. really appreciated it. 
![Screenshot 2023-10-29 at 21 13 52](https://github.com/xpilot-project/xpilot/assets/149291417/21fed61b-21f7-459e-9d49-0e27ce3bb3ad)

**Comment by justinshannon** [comment]
Happy to help. Enjoy.
