### ISSUE TITLE
Engine Sounds in Headset

### ISSUE THREAD

**Issue by Trodaiche** [xpilot-project/xpilot#181]
Im hearing the engine sounds of other online aircraft in my headset.

Is there a way that these sounds can be moved to external speakers?

**Comment by justinshannon** [comment]
The aircraft sounds are routed to your computer’s default output audio device. There’s no way to specify which device they are routed to in the xPilot settings.

**Comment by Trodaiche** [comment]
Ah OK thanks anyway

**Comment by justinshannon** [comment]
I’ll keep this open as a possible future enhancement.

**Comment by Trodaiche** [comment]
Thanks

**Comment by justinshannon** [comment]
This is now available in beta 50.

**Comment by Trodaiche** [comment]
Super thanks again
