### ISSUE TITLE
Updating XPMP2 might fix Linux XP hanging after "global TCAS override" with XP 12.0.8-beta-1

### ISSUE THREAD

**Issue by jonaseberle** [xpilot-project/xpilot#182]
[Like some LiveTraffic Linux users](https://forums.x-plane.org/index.php?/forums/topic/296584-livetraffic-freezes-xp-1208beta1-on-taking-over-tcas/), I also had a hanging sim on startup with X-Plane 12.0.8-beta-1 with this last line in the log:

```
0:02:19.930 I/PLG: The plugin xPilot 2.0.0-beta.49 is setting global TCAS override to 1.
```

I cannot reproduce that in my vanilla instance with only xPilot as single plugin, though. And in my full sim it would not happen always.

@TwinFan fixed it in LiveTraffic by updating his XPMP2 library (thanks!). It seems to be [this commit](https://github.com/TwinFan/XPMP2/commit/d472f400811fb89ea72a742765ffb294dcdcfb70).

**Comment by justinshannon** [comment]
This fix has been ported over to beta 50 (which was just released).
