### ISSUE TITLE
comX_on_headset initialize to 0

### ISSUE THREAD

**Issue by ogruetzmann** [xpilot-project/xpilot#183]
The two new datarefs seem to always initialize to 0, despite in xPilot the outputs are routed to the headset.

Also, changing them from within the sim does not change the output in xPilot.

Oliver

**Comment by ogruetzmann** [comment]
First test on the network, it also seems that the audio is by default routing to the speakers. Need to press the toggle twice (->spekers->headset) to get the output on my headset.

**Comment by justinshannon** [comment]
This is fixed in beta 52.
