### ISSUE TITLE
No Mikrophone input 

### ISSUE THREAD

**Issue by Monoid12** [xpilot-project/xpilot#184]
Hey Folks,

I updated pilot yesterday to beta.50. After that, I had no microphone input. Any solutions?

System: MacBook Pro M1

Michel

**Comment by DanielRoehrle** [comment]
Same for me, no microphone input after updating. 
I'm using a Mac Mini M1
Daniel

**Comment by justinshannon** [comment]
This should be fixed in the beta 51, which was just released.
