### ISSUE TITLE
Xpilot quits unexpectedly

### ISSUE THREAD

**Issue by osca644** [xpilot-project/xpilot#185]
after todays update my x pilot is broken
<img width="276" alt="Screenshot 2023-11-16 at 2 22 40 PM" src="https://github.com/xpilot-project/xpilot/assets/151082463/777e98c7-7145-421d-984d-1cfe430e6223">Translated Report (Full Report Below)
-------------------------------------

Process:               xPilot [1836]
Path:                  /Applications/xPilot/xPilot.app/Contents/MacOS/xPilot
Identifier:            
Version:                ()
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-11-16 14:20:24.2102 -0600
OS Version:            macOS 13.6 (22G120)
Report Version:        12
Anonymous UUID:        D7A23D5D-8C6D-2AFD-5C23-D0966E7A4D98

Time Awake Since Boot: 3800 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /usr/local/opt/openssl@3/lib/libssl.3.dylib
Referenced from: <CF2CA454-699F-333D-8429-4B615E8366EE> /Applications/xPilot/xPilot.app/Contents/MacOS/xPilot
Reason: tried: '/usr/local/opt/openssl@3/lib/libssl.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/openssl@3/lib/libssl.3.dylib' (no such file), '/usr/local/opt/openssl@3/lib/libssl.3.dylib' (no such file), '/usr/lib/libssl.3.dylib' (no such file, not in dyld cache)
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                          	    0x7ff80b174c52 __abort_with_payload + 10
1   dyld                          	    0x7ff80b18efd7 abort_with_payload_wrapper_internal + 82
2   dyld                          	    0x7ff80b18f009 abort_with_payload + 9
3   dyld                          	    0x7ff80b1138f0 dyld4::halt(char const*) + 375
4   dyld                          	    0x7ff80b110b71 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 4526
5   dyld                          	    0x7ff80b10f3bd start + 1805

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000002000209  rbx: 0x0000000000000000  rcx: 0x00007ff7b85114b8  rdx: 0x00007ff7b8511920
  rdi: 0x0000000000000006  rsi: 0x0000000000000001  rbp: 0x00007ff7b8511500  rsp: 0x00007ff7b85114b8
   r8: 0x00007ff7b8511520   r9: 0x0000000000000000  r10: 0x0000000000000076  r11: 0x0000000000000246
  r12: 0x0000000000000076  r13: 0x00007ff7b8511920  r14: 0x0000000000000001  r15: 0x0000000000000006
  rip: 0x00007ff80b174c52  rfl: 0x0000000000000246  cr2: 0x000000010aeff000
  
Logical CPU:     0
Error Code:      0x02000209 
Trap Number:     133

Binary Images:
       0x1079ed000 -        0x10a0a8fff xPilot (*) <cf2ca454-699f-333d-8429-4b615e8366ee> /Applications/xPilot/xPilot.app/Contents/MacOS/xPilot
    0x7ff80b109000 -     0x7ff80b1a15ef dyld (*) <3df96f32-b9c9-3566-a6b7-4daebc6d6563> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=222.5M resident=0K(0%) swapped_out_or_unallocated=222.5M(100%)
Writable regions: Total=8596K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8596K(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
VM_ALLOCATE                          8K        2 
__DATA                             795K        3 
__DATA_CONST                      1028K        2 
__DATA_DIRTY                         7K        1 
__LINKEDIT                       183.2M        3 
__TEXT                            39.3M        2 
dyld private memory                260K        2 
shared memory                        4K        1 
===========                     =======  ======= 
TOTAL                            288.6M       18 

-----------
Full Report
-----------

{"app_name":"xPilot","timestamp":"2023-11-16 14:20:24.00 -0600","app_version":"","slice_uuid":"cf2ca454-699f-333d-8429-4b615e8366ee","build_version":"","platform":1,"bundleID":"","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.6 (22G120)","roots_installed":0,"name":"xPilot","incident_id":"AEEAD53B-020E-482D-866F-2356E5980926"}
{
  "uptime" : 3800,
  "procRole" : "Background",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "iMac18,3",
  "coalitionID" : 1290,
  "osVersion" : {
    "train" : "macOS 13.6",
    "build" : "22G120",
    "releaseType" : "User"
  },
  "captureTime" : "2023-11-16 14:20:24.2102 -0600",
  "incident" : "AEEAD53B-020E-482D-866F-2356E5980926",
  "pid" : 1836,
  "cpuType" : "X86-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-11-16 14:20:23.4139 -0600",
  "procStartAbsTime" : 3861647721747,
  "procExitAbsTime" : 3862443873256,
  "procName" : "xPilot",
  "procPath" : "\/Applications\/xPilot\/xPilot.app\/Contents\/MacOS\/xPilot",
  "bundleInfo" : {"CFBundleShortVersionString":"","CFBundleVersion":"","CFBundleIdentifier":""},
  "storeInfo" : {"deviceIdentifierForVendor":"E1031636-B0F8-5D66-8F8F-AF0571FA4AFE","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "crashReporterKey" : "D7A23D5D-8C6D-2AFD-5C23-D0966E7A4D98",
  "codeSigningID" : "",
  "codeSigningTeamID" : "X3TMVGC3W9",
  "codeSigningFlags" : 570499857,
  "codeSigningValidationCategory" : 6,
  "codeSigningTrustLevel" : 0,
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: \/usr\/local\/opt\/openssl@3\/lib\/libssl.3.dylib","Referenced from: <CF2CA454-699F-333D-8429-4B615E8366EE> \/Applications\/xPilot\/xPilot.app\/Contents\/MacOS\/xPilot","Reason: tried: '\/usr\/local\/opt\/openssl@3\/lib\/libssl.3.dylib' (no such file), '\/System\/Volumes\/Preboot\/Cryptexes\/OS\/usr\/local\/opt\/openssl@3\/lib\/libssl.3.dylib' (no such file), '\/usr\/local\/opt\/openssl@3\/lib\/libssl.3.dylib' (no such file), '\/usr\/lib\/libssl.3.dylib' (no such file, not in dyld cache)"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":53522,"threadState":{"r13":{"value":140701925972256},"rax":{"value":33554953},"rflags":{"value":582},"cpu":{"value":0},"r14":{"value":1},"rsi":{"value":1},"r8":{"value":140701925971232},"cr2":{"value":4478464000},"rdx":{"value":140701925972256},"r10":{"value":118},"r9":{"value":0},"r15":{"value":6},"rbx":{"value":0},"trap":{"value":133},"err":{"value":33554953},"r11":{"value":582},"rip":{"value":140703314693202,"matchesCrashFrame":1},"rbp":{"value":140701925971200},"rsp":{"value":140701925971128},"r12":{"value":118},"rcx":{"value":140701925971128},"flavor":"x86_THREAD_STATE","rdi":{"value":6}},"frames":[{"imageOffset":441426,"symbol":"__abort_with_payload","symbolLocation":10,"imageIndex":1},{"imageOffset":548823,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":82,"imageIndex":1},{"imageOffset":548873,"symbol":"abort_with_payload","symbolLocation":9,"imageIndex":1},{"imageOffset":43248,"symbol":"dyld4::halt(char const*)","symbolLocation":375,"imageIndex":1},{"imageOffset":31601,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":4526,"imageIndex":1},{"imageOffset":25533,"symbol":"start","symbolLocation":1805,"imageIndex":1}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4422815744,
    "CFBundleShortVersionString" : "",
    "CFBundleIdentifier" : "",
    "size" : 40615936,
    "uuid" : "cf2ca454-699f-333d-8429-4b615e8366ee",
    "path" : "\/Applications\/xPilot\/xPilot.app\/Contents\/MacOS\/xPilot",
    "name" : "xPilot",
    "CFBundleVersion" : ""
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703314251776,
    "size" : 624112,
    "uuid" : "3df96f32-b9c9-3566-a6b7-4daebc6d6563",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 140703313629184,
  "size" : 21474836480,
  "uuid" : "2434d7b8-6144-3aef-92fd-a483c33f40d2"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=222.5M resident=0K(0%) swapped_out_or_unallocated=222.5M(100%)\nWritable regions: Total=8596K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8596K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8192K        1 \nVM_ALLOCATE                          8K        2 \n__DATA                             795K        3 \n__DATA_CONST                      1028K        2 \n__DATA_DIRTY                         7K        1 \n__LINKEDIT                       183.2M        3 \n__TEXT                            39.3M        2 \ndyld private memory                260K        2 \nshared memory                        4K        1 \n===========                     =======  ======= \nTOTAL                            288.6M       18 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "logWritingSignature" : "fc62188a64f20a71a80b7d5fd4ac2eb0aeb0fd0e",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "6297d96be2c9387df974efa4",
      "factorPackIds" : {

      },
      "deploymentId" : 240000014
    },
    {
      "rolloutId" : "60186475825c62000ccf5450",
      "factorPackIds" : {

      },
      "deploymentId" : 240000062
    }
  ],
  "experiments" : [

  ]
}
}

Model: iMac18,3, BootROM 515.0.0.0.0, 4 processors, Quad-Core Intel Core i7, 4.2 GHz, 16 GB, SMC 2.41f2
Graphics: Radeon Pro 580, Radeon Pro 580, PCIe, 8 GB
Display: iMac, Retina 5K (5120 x 2880), Main, MirrorOff, Online
Memory Module: BANK 0/DIMM0, 8 GB, DDR4 SO-DIMM, 2400 MHz, 0x802C, 0x3841544631473634485A2D324733423220202020
Memory Module: BANK 1/DIMM0, 8 GB, DDR4 SO-DIMM, 2400 MHz, 0x802C, 0x3841544631473634485A2D324733423220202020
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x16F), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1772.1)
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: APPLE HDD ST2000DM001, 2 TB
USB Device: USB30Bus
USB Device: USB3.1 Hub
USB Device: USB2.1 Hub
USB Device: LucidSound Battery Charger
USB Device: Saitek Pro Flight Rudder Pedals
USB Device: Bluetooth USB Host Controller
USB Device: FaceTime HD Camera (Built-in)
USB Device: Alpha Flight Controls
USB Device: Arduino Leonardo
USB Device: Saitek Pro Flight Quadrant
USB Device: G-DRIVE mobile USB-C
Thunderbolt Bus: iMac, Apple Inc., 41.5

**Comment by justinshannon** [comment]
Sorry about that. I just pushed a new version that fixes this. You will need to manually download beta 51 and install it.

https://github.com/xpilot-project/xpilot/releases/latest
