### ISSUE TITLE
Xpilot says "HostNotFoundError: Host not found"

### ISSUE THREAD

**Issue by musabhamid** [xpilot-project/xpilot#186]
Hello. everytime i try to log on to xpilot, i keeo getting a msg that says "HostNotFoundError: Host not found" i have the latest beata of xpilot, i dont know why it says this and i dont now what it means. anyone know what this is?

**Comment by musabhamid** [comment]
![Uploading Screenshot 2023-11-18 at 11.34.34.png…]()

**Comment by musabhamid** [comment]
![Uploading Screenshot 2023-11-18 at 11.54.50.png…]()

**Comment by justinshannon** [comment]
Can you post a screenshot? What is your OS?

**Comment by musabhamid** [comment]
That’s okay! I sorted it out. I needed to instal CSL! :)

**Comment by justinshannon** [comment]
Are you still getting the “HostNotFoundError” error?

**Comment by musabhamid** [comment]
No sir. If I get it will let you know thanks

**Comment by justinshannon** [comment]
Sounds good. I'm going to close this out. If you encounter the issue again, feel free to open a new issue.
