### ISSUE TITLE
Allow underscore in callsign for Observer mode

### ISSUE THREAD

**Issue by Jarlath-tg** [xpilot-project/xpilot#187]
In 2.0b50 the function "Allow only alphanumeric characters in the callsign" was announced. 
If the observer option is enabled at least the underscore should be allowed according to C3 - VATSIM Code of Conduct.

**Comment by justinshannon** [comment]
This section of the CoC only applies to controllers, not pilots. xPilot callsigns will continue to only allow alphanumeric characters.
