### ISSUE TITLE
The beginning of audio transmission is trimmed under some unknown environments

### ISSUE THREAD

**Issue by asdf1280** [xpilot-project/xpilot#188]
When I'm using xPilot for VATSIM, I can't hear the beginning part of each transmission. For example, when the controller or other pilot says "United 123" as soon as they click PTT, I only hear "ted 123". This doesn't happen when playing MSFS with vPilot, and didn't happen with very old xPilot (a few years ago).

[Audio heard in vPilot](https://youtu.be/6LCcwvSVHu8) check from 0:55

[Audio heard in xPilot](https://youtu.be/rEWIEsESK8s) check from 0:25

The issue was reproduced in following audio drivers: Logitech G560 audio driver, Realtek HD Audio

OS: Windows 11 23606.1000

Reproducible in following network conditions: Connecting to the Internet through router, connecting the PC directly to the modem, connecting with Cloudflare WARP, connecting with VPN, connecting to mobile hotspot 5G network

Reproducible regardless of 'Realistic Radio Effects' and 'HF Squelch' settings

**Comment by justinshannon** [comment]
Thanks for submitting this detailed bug report. I think I am able to reproduce this on my local setup, but so far, I am not sure what is causing this. I will continue to investigate...

**Comment by justinshannon** [comment]
Fixed in beta 53.
