### ISSUE TITLE
Microphone does not work - Beta 52

### ISSUE THREAD

**Issue by jnorment** [xpilot-project/xpilot#190]
I believe this issue started sometime around Beta 49 or 50 but I have not been able to use the microphone features of X-Pilot for some time now. They did work previously but I cannot replicate which version it worked on before. 

Previously, I utilized Voicemeeter and have since uninstalled it. I re-installed all of my audio drivers, disable Game Bar, disable ASUS AI Noise Cancellation and reinstalled iCue (I use Corsair headphones).

The microphone works fine in any other application.

I checked and Windows 11 Privacy Settings for the microphone do not have it restricted.

**Comment by justinshannon** [comment]
Can you upload the xPilot AFV logs? You can find these by entering the command `.appdata` into xPilot, which will open the folder where the log files are saved.

**Comment by Huijaaja42** [comment]
I'm having a similar issue but with any version after Beta 49, logs in Discord. https://discord.com/channels/707375502851309598/1225331659088597024

**Comment by jnorment** [comment]
I apologize @justinshannon I can upload logs for you this evening
