### ISSUE TITLE
[Feat Request] separate command in X-Plane for splitting audio

### ISSUE THREAD

**Issue by ChrisXPP** [xpilot-project/xpilot#201]
Hi Justin,

is it possible to add a specific command in X-Plane which can be mapped to a joystick/keyboard button for splitting audio into separate channels (which is now possible, many thanks for implementing that :-) )?

This way changing between splitted and non-splitted audio receiving would be a bit more "convenient" than switching to the main xPilot interface... :-)

Greetings,
Christoph

**Comment by justinshannon** [comment]
This will be available in the next release: b03cd5c33d896182aec40a747cea6791788730dc
