### ISSUE TITLE
Xpilot cannot select an aircraft 

### ISSUE THREAD

**Issue by coxyyy** [xpilot-project/xpilot#203]
When i try to select an aircraft xpilot does'nt select anything and just uses the default plane

**Comment by justinshannon** [comment]
I'm not really sure what you mean by this. Can you post a screenshot of what you're doing and the results you're getting vs your expected result? 

It also might be easier if you just join the xPilot Discord and post there... The GitHub is meant more for actual bug reports, not support requests.
