### ISSUE TITLE
Error in new 3.0.1 version

### ISSUE THREAD

**Issue by DevonFly** [xpilot-project/xpilot#212]
I attach screenshot showing loading error. I now cannot use the older version as it says it is invalid.
![x-pilot error](https://github.com/xpilot-project/xpilot/assets/53476922/5304e1c2-bab5-4be2-baea-ef6d0e494bf8)

**Comment by justinshannon** [comment]
Try manually re-downloading the installer and running it. If you still get the error, try running the installer as an administrator.

https://github.com/xpilot-project/xpilot/releases/download/v3.0.1/xPilot-3.0.1-Windows.exe
