### ISSUE TITLE
xPilot incompatible Windows 10 x64

### ISSUE THREAD

**Issue by CptDre** [xpilot-project/xpilot#214]
After installing, trying to exe the .exe file, I get error (0x000007b) and after running the troubleshooter, the result is that it is Incompatible for my computer. Any solutions? I've tried uninstalling and reinstalling it about 4 times, but still nothing.

![image](https://github.com/xpilot-project/xpilot/assets/174563653/d807ef70-3899-491b-9de7-ee86994bf800)

![image](https://github.com/xpilot-project/xpilot/assets/174563653/37871bf6-794b-4fa1-8ddc-00d65b6a5d74)

**Comment by justinshannon** [comment]
Try installing the Windows C++ Redistributable package. Here's the direct link from Microsoft's website: https://aka.ms/vs/17/release/vc_redist.x64.exe

Or you can grab the link from the Microsoft website (just make sure you download the x64 version): https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022
