### ISSUE TITLE
Error Install

### ISSUE THREAD

**Issue by Simloife** [xpilot-project/xpilot#215]
![xpilot error](https://github.com/xpilot-project/xpilot/assets/174961170/78ce80b8-40d0-4f89-b172-31a788887ceb)

Hi i attempted to install xpilot 3.0 and this error came up any ideas ??new to xpilot ....
appreciate any help thanks

**Comment by Simloife** [comment]
Windows 8 64bit if that helps i knwo its not helping me lol

**Comment by justinshannon** [comment]
Windows 8 is not supported. xPilot requires Windows 10 or newer. https://docs.xpilot-project.org/docs/system-requirements
