### ISSUE TITLE
Virus in Xpilot 

### ISSUE THREAD

**Issue by rhian15** [xpilot-project/xpilot#219]
Hi Justin, id love to use your program but when i download it and run it it says it has detected malware. I really wanna use it but dont wanna risk my computer.

**Comment by justinshannon** [comment]
As long as you’re downloading it directly from the xPilot website (which actually redirects you to the xPilot GitHub page to download) then you’re probably fine. I’ve not received any reports of the executable being tampered with. It’s most likely just an over reactive antivirus.
