### ISSUE TITLE
 [Beta 9] Change to "upgrade" mode didn't work

### ISSUE THREAD

**Issue by ChrisXPP** [xpilot-project/xpilot#22]
Hi,

after upgrading from beta 8 to beta 9 on Win 11 I noticed the entry in the app list for beta 8 still existed (manually removed via the registry editor).

**Comment by justinshannon** [comment]
Unfortunately, this change does not retroactively remove entries for previous versions. It will only work for beta 9 or newer versions. 

I’ll update the release notes to make this more clear.

**Comment by ChrisXPP** [comment]
> Unfortunately, this change does not retroactively remove entries for previous versions. It will only work for beta 9 or newer versions.
> 
> I’ll update the release notes to make this more clear.

Thanks for that info! (👍 )
