### ISSUE TITLE
xPilot v2.0.0-beta.9

### ISSUE THREAD

**Issue by rwaelty** [xpilot-project/xpilot#25]
On the Version xPilot v2.0.0-beta.9 it is not possible to activate the connect button on all Your Apple Mac's with Mac OS Monterey. We went back to beta.8. With this version no problem.

**Comment by justinshannon** [comment]
This issue has been resolved in beta 10.

**Comment by rwaelty** [comment]
Good Morning Justin

Thanks allot. For the Mac Your xPilot is by far the best program to use for Vatsim. Also all other connected aircrafts that are shown are impressive. Thanks for Your great and beautiful work. All the best for You and Your Team.
Kind regards
Rolf 

IOS 15
