### ISSUE TITLE
Altitude Issues

### ISSUE THREAD

**Issue by Aviat0r4life** [xpilot-project/xpilot#29]
Two flights in a row other aircraft have not been showing at the correct altitude. This was two separate flights, connections, and happened on both velocity and the main servers. Fellow pilot was above my altitude however, showing 5-10 thousand below me and I was showing well below them as well.

**Comment by justinshannon** [comment]
I need a couple of things...

1. Version of xPilot you're running
2. Plugin and Network Log from this session. Let me know specific callsigns. You can find these in the same folder where the AppConfig.json file is located. See the FAQ if you're not familiar: https://beta.xpilot-project.org/#/faq
3. Ideally, if you're able to reproduce it again, provide a screenshot that shows what their correct altitude is (i.e. in VATSpy) vs what you're seeing in xPilot.

**Comment by Aviat0r4life** [comment]
1. xPilot Version 1.3.38
2. AAL313 and AAL1311
 {
    "AlertDirectRadioMessage": true,
    "AlertDisconnect": true,
    "AlertNetworkBroadcast": true,
    "AlertPrivateMessage": true,
    "AlertRadioMessage": true,
    "AlertSelcal": true,
    "AudioApi": "Windows DirectSound",
    "AudioEffectsDisabled": true,
    "AutoModeC": false,
    "CachedServers": [
        {
            "address": "137.184.8.6",
            "name": "USA-WEST"
        },
        {
            "address": "178.62.56.106",
            "name": "UK"
        },
        {
            "address": "167.99.46.165",
            "name": "AMSTERDAM"
        },
        {
            "address": "188.166.248.163",
            "name": "SINGAPORE"
        },
        {
            "address": "159.65.171.192",
            "name": "USA-EAST"
        },
        {
            "address": "178.128.193.227",
            "name": "GERMANY"
        },
        {
            "address": "159.203.44.51",
            "name": "CANADA"
        }
    ],
    "Com1Volume": 95,
    "Com2Volume": 100,
    "HFSquelchEnabled": true,
    "HomeAirport": "KSWO",
    "InputDevice": "Microphone (Logitech G533 Gaming Headset)",
    "KeepWindowVisible": false,
    "Name": "Danny",
    "OutputDevice": "Speakers (Logitech G533 Gaming Headset)",
    "RecentConnection": {
        "Callsign": "UAL2275",
        "SelcalCode": "",
        "TypeCode": "B738"
    },
    "ServerName": "USA-WEST",
    "SilenceModelInstall": true,
    "VatsimId": "1159469",
    "VatsimPassword": "AwLyRtFyAqbCXPDMok9rkeo=",
    "VisualMachines": [
    ],
    "WindowConfig": {
        "Height": 377,
        "Maximized": false,
        "Width": 1012,
        "X": 449,
        "Y": 487
    },
    "XplaneNetworkAddress": "127.0.0.1",
    "XplanePluginPort": 53100,
    "XplaneUdpPort": 49000
}
3. We can try time may be an issue.

**Comment by justinshannon** [comment]
You pasted your AppConfig.json. That's not what I need. I need the Network and Plugin log, which are **in the same folder** where the AppConfig.json can be found (there is a NetworkLog and PluginLog folder, with the respective logs within).
