### ISSUE TITLE
Flight plan window possibly exceeds monitor

### ISSUE THREAD

**Issue by ChrisXPP** [xpilot-project/xpilot#30]
Hi,

the flight plan window in the xPilot client exceeds the border of the monitor (depending on the resolution). In this case it's neither possible to drag the window nor to even close it... only solution: force xPilot to close via the task manager & restart.
I think there was a similar issue with the settings window in an earlier beta?

![flight_plan_window](https://user-images.githubusercontent.com/74152765/147877920-86e5c2ea-7123-4097-bad5-d87ae34d0d94.jpg)

**Comment by justinshannon** [comment]
I've decided I'm going to remove flight plan filing from the next version — completely rip off the band aid now, rather than later.
