### ISSUE TITLE
Bulit in flight plan issue

### ISSUE THREAD

**Issue by kod3ch** [xpilot-project/xpilot#31]
Hi, 
Today me and my friend decided to fly together on zibo 738 3.51.11 with smartcopilot. He enters callsing RYR704 and sucseccfully connects and files a flight plan. I take RYR704B callsing, checked shared cockpit mode and connected. After that I tried to file a fpl via client menu but i can't really enter anything because almost every second all entry areas refreshes with random flight plans data in it.
I tried file fpl on web page and then load it into app but it doesnt help.
Here is video demonstraion of that issue:
https://user-images.githubusercontent.com/18100538/147890121-4a4cab12-31d6-4267-bdc7-5c48d02c39fa.mp4

**Comment by justinshannon** [comment]
The flight plan form in the client will be going away again in the next beta.
