### ISSUE TITLE
xPilot not detecting sim crash

### ISSUE THREAD

**Issue by zachbf** [xpilot-project/xpilot#33]
my xPlane crashed when loading a new aircraft.
xPilot (beta 12) did not detect the simcrash as it previously has and froze to the usual "application is not responding, close or wait".

**Comment by justinshannon** [comment]
Did the xPilot client successfully establish connection with X-Plane before the crash?

**Comment by zachbf** [comment]
Yep, I was connected to the velocity test server, when I conducted the aircraft change.

**Comment by justinshannon** [comment]
Might be a long shot, but can you look in the folder where the xPilot client is installed and see if there is a `.sentry-native` folder? If there is, can you look inside and see if there's a `.dmp` file? Unfortunately, I don't see any crash reports in Sentry, so it may not have triggered anything when it crashed.

**Comment by justinshannon** [comment]
Bummer! Without some sort of dmp file, I can't really begin to diagnose what part of the code caused it to freeze and crash.

**Comment by zachbf** [comment]
I'll see if I can replicate it for you a little later, and I won't force close xPilot to see if can possibly generate the error.

**Comment by justinshannon** [comment]
I'm going to close this out. If you still experience this with the latest version (beta 23), feel free to re-open this.
