### ISSUE TITLE
xPilot isn't setting on-ground flag correctly

### ISSUE THREAD

**Issue by skiselkov** [xpilot-project/xpilot#34]
xPilot must set this flag correctly for contacts:
`sim/cockpit2/tcas/targets/position/weight_on_wheels int[64]`
It appears, this is currently always set to '1', causing the X-TCAS plugin to think all TCAS contacts are on the ground (and thus not display them, or generate TAs or RAs against them).

**Comment by justinshannon** [comment]
Support for this dataref has been added in beta 16.
