### ISSUE TITLE
[Feature Request] Add ability for aircraft addons to see when a SELCAL alert is received

### ISSUE THREAD

**Issue by pilsnerish** [xpilot-project/xpilot#35]
Presume could be done via dataref similar to PTT/RX. Or inter-plugin API.

**Comment by pilsnerish** [comment]
Secondary request: Allow SELCAL code itself to be read via dataref, if set

**Comment by justinshannon** [comment]
Two new datarefs will be added to the next version.

`xpilot/selcal`: The SELCAL code (represented with no spaces or dashes)
`xpilot/selcal_received`: Value will change to `1` when a SELCAL alert is received. It will reset to `0` after 1 second.

**Comment by WizballCvS** [comment]
Suggestion to this new feature.
Maybe add a way for xpilot to detect that the aircraft is supporting selcal. So you dont need to manually disable the selcal alert in xpilot to avoid dual alert from xpilot and the aircraft.
When xpilot detect that the aircraft is supporting selcal, xpilot will not play the selcal alert.

could maybe also just be a writable dataref i.e. xpilot/selcal_mute.. or something like that.
