### ISSUE TITLE
Significant framedrop in xplane 11

### ISSUE THREAD

**Issue by anthraxn8b** [xpilot-project/xpilot#36]
Using Beta 2.0.0 16 on Win10.

Using the notification area from the plugin and/or having the xpilot window on top drops the sim framerate significantly.

So having 30fps it drops it to 19fps what leads to a vatsim disconnect.

Any ideas?

**Comment by justinshannon** [comment]
I am unable to reproduce a frame rate drop when using the notification area or by having the xPilot client open on top of X-Plane. This is also the first time I've heard of this happening, which leads me to believe it's a hardware deficiency on your end. 

I don't have any ideas, sorry.
