### ISSUE TITLE
xPilot crashes the X-plane SIM because of a CSL problem

### ISSUE THREAD

**Issue by Chroode** [xpilot-project/xpilot#38]
Hi,
I downloaded xPilot 2 days ago with the automatic CSL download and it seemed to work fine for the two times I logged on. 
Starting yesterday X-Plane 11.55 started crashing after loading the plane. I also ended up with 3 shortcuts to SAM Global Trees, etc. It also wrote those to the top of my scenery ini files.
I tracked it down to removing the entries in the CSL. I then uninstalled and reinstalled xPilot telling it not to auto download the BlueBell, and started the sim. It loaded the plane and complained there was no CSL. I then accessed the settings menu and made sure the mapping was correct to the CSL file.       X-plane/Resources/Plugins/xPilot/Resources/CSL       I then quit the X-Plane.
I manually entered the bluebell aircraft to the CSL file.
I started X-Plane again and once again the sim crashed upon loading the plane. 
At this point I am stumped.
Any suggestions?
Thanks 
Chris
The log is attached below but her is the bottom half:

0:01:10.326 xPilot/XPMP2 INFO  XPMPMultiplayer.cpp:154/XPMPMultiplayerInit: XPMP2 2.30 initializing under X-Plane version 11550/Vulkan and XPLM version 303
0:01:10.326 xPilot/XPMP2 WARN  CSLModels.cpp:397/AddMatchCriteria: Line 19: Different aircraft type (A320 instead of A321) for model 'BB_German_Air_Express_VA A321_Hannover' ignored, rest  processed
0:01:10.326 xPilot/XPMP2 WARN  CSLModels.cpp:397/AddMatchCriteria: Line 25: Different aircraft type (A320 instead of A321) for model 'BB_German_Air_Express_VA A321_Karlsruhe' ignored, rest  processed
0:01:10.326 xPilot/XPMP2 WARN  CSLModels.cpp:397/AddMatchCriteria: Line 37: Different aircraft type (B350 instead of BE20) for model 'BB_WAT_VA BE20_WAT' ignored, rest  processed
0:01:10.326 xPilot/XPMP2 WARN  CSLModels.cpp:397/AddMatchCriteria: Line 68: Different aircraft type (B748 instead of B744) for model 'BB_WAT_VA B744_WAT' ignored, rest  processed
0:01:10.326 xPilot/XPMP2 WARN  CSLModels.cpp:397/AddMatchCriteria: Line 79: Different aircraft type (B753 instead of B752) for model 'BB_WAT_VA B752_WAT' ignored, rest  processed
0:01:10.326 xPilot/XPMP2 WARN  CSLModels.cpp:397/AddMatchCriteria: Line 85: Different aircraft type (B763 instead of B762) for model 'BB_WAT_VA B763_WAT' ignored, rest  processed
0:01:10.326 xPilot/XPMP2 WARN  CSLModels.cpp:397/AddMatchCriteria: Line 141: Different aircraft type (E195 instead of E190) for model 'BB_WAT_VA E195_WAT' ignored, rest  processed
0:01:10.326 xPilot/XPMP2 WARN  CSLModels.cpp:397/AddMatchCriteria: Line 157: Different aircraft type (MD88 instead of MD82) for model 'BB_WAT_VA MD83_WAT' ignored, rest  processed
0:01:10.326 I/PLG: The plugin xPilot 2.0.0-beta.16 is setting global TCAS override to 1.
0:01:10.326 xPilot: Now listening on port 53100
0:01:10.326 E/SYS: THREAD FATAL ASSERT: rel_assert Error! Possibly an out of range vector! Attach the debugger and see who called this!
0:01:10.326 E/SYS: THREAD FATAL ASSERT: !THREAD_is_inited() || THREAD_is_main_thread()
0:01:10.326 E/SYS: THREAD FATAL ASSERT: XPCreateGuiPluginWindow
0:01:10.326 E/SYS: THREAD FATAL ASSERT: Please report this to Laminar Research.
0:01:10.326 E/SYS: THREAD FATAL ASSERT: C:\jenkins\design-triggered\source_code\engine\plugins\glue\XPCallbacks.cpp:1769
0:01:14.966 G64:  core: Run: [OnBoot]
0:01:14.966 G64: debug: 	GK: Auto license update is on.
0:01:14.966 G64: debug: 	GK: License days remaining: 6.07 - No update required.
0:01:14.966 G64: debug: 	GK: Update required when <= 2.00 days.
0:01:14.966 G64:  core: Run: [OnFirstFrame]
--=={This application has crashed!}==--
(Art controls are modified.)

[Log 01-16-22.txt](https://github.com/xpilot-project/xpilot/files/7878476/Log.01-16-22.txt)
s

**Comment by justinshannon** [comment]
https://beta.xpilot-project.org/#/xplane-crash

**Comment by Chroode** [comment]
[crash_report_01_18_2022_16_38_10.rpt.zip](https://github.com/xpilot-project/xpilot/files/7890959/crash_report_01_18_2022_16_38_10.rpt.zip)

Here is the crash report

**Comment by Chroode** [comment]
[crash_report_01_18_2022_16_38_10.rpt.zip](https://github.com/xpilot-project/xpilot/files/7890966/crash_report_01_18_2022_16_38_10.rpt.zip)
Here is the log

**Comment by justinshannon** [comment]
xPilot is not the cause for this crash. The crash file only tells me that `win.xpl` caused X-Plane to crash. You have 36 plugins installed that have a plugin name of `win.xpl` (the xPilot plugin file is called `xPilot.xpl`). You'll have to remove each `win.xpl` plugin one by one until you can find which one is causing X-Plane to crash.

```
X-Plane.exe!00007ff749f55f47()
X-Plane.exe!00007ff749b8f799()
XPLM_64.dll!00007ffbd934836e()
XPWidgets_64.dll!00007ffbe04288dc()
[Frames may be missing, no binary loaded for win.xpl]
win.xpl!000002013e5ed614()
```
