### ISSUE TITLE
Some problem with FlywithLua scripts

### ISSUE THREAD

**Issue by marloscaida** [xpilot-project/xpilot#39]
I downloaded and installed the latest Beta version of XPilot. The truth is that I didn't have any problems regarding its functionality, but a script that worked well with the FlyWithLua plugin (latest version) stopped working. 
This is V-Speed Callouts for Toliss A319 2019.06.03 (a very simple script). 
I don't know what else can affect the XPilot plugin that installs the Beta version of the product. 
I went back to the stable version and the problem was fixed. 
This is not a complaint, rather it is a warning to developers. I hope it is useful to you.
Thank very much for your great work.
Regards
Carlos Maida
Ushuaia - Argentina

**Comment by justinshannon** [comment]
The audio rendering system (OpenAL) has been replaced with FMOD in beta 18. Let me know if you're still having issues with the latest version of xPilot.

**Comment by marloscaida** [comment]
The issue was solved!
Thanks very much.
carlos
