### ISSUE TITLE
frequency list should auto-fix bad frequencies

### ISSUE THREAD

**Issue by arnotixe** [xpilot-project/xpilot#40]
Tried to manually tune a frequency today, and heard nothing.

Right-clicking the offending frequency and Tune to COM1 did work, but I saw xPilot autocorrected it (129.420) to 129.425.

Suspected xPilot for no reason… But I have an idea for a small improvement anyway:

**In short, I suggest the frequency list be autocorrected so that nonexisting frequencies are rounded up 5kHz**

This would mean that 129.420 would be displayed as 129.425 instead (which is the frecuency tuned when "tune to COM1" anyway)

- I know the controller below said it should be .420 (he set that but in reality .420 doesn't exist). His software probably auto-corrected that without telling him (not xPilot's problem).
- I know radios should not allow .420 to be selected either (also not xPilot's problem).

No. 2 image below shows missing frequencies that may be tunable in sims and should be autocorrected.

![badtune](https://user-images.githubusercontent.com/500938/151708475-e1bbe55f-46d8-4267-a5bc-868fed26e865.png)
![eurocontrol-missingchannels](https://user-images.githubusercontent.com/500938/151709655-5cfd9c89-b07f-4d3d-97f7-c1ea6c31ddcc.png)

**Comment by ChrisXPP** [comment]
Officially there's no frequency ending on .420, neither on 25 kHz nor on 8.33 kHz spacing... it's some kind of "VATSIMaism". I agree xPilot should (could) auto-round this up to .xx5, but the main cause definitely is on the ATC side - they simply should stop "abbreviating" frequencies (i .e. .425 to .420) since that's completely unnecessary.

**Comment by arnotixe** [comment]
yeah, I definitely assumed ATC would enter an existing, tunable frequency. :smile:

Only other argument I could think of would be that the list would correspond to the tuned frequency, see first image above. It's slightly strange if you read the tuned frequency first and then look for it in the list - makes you think you're on a different one from those on the list.

**Comment by ManuelPick** [comment]
The issue was afaik that EuroScope rounds the last digit. So if you send contact me's with .425 as your frequency, the contact me message would display .430 which wouldn't work.
I don't know if that's fixed though.

**Comment by meltinglava** [comment]
This is an issue from back when Vatsim only supported 2 decimal digits. So if you look at the vatsim status API you find that freqs there end in .420 as well. Vatsim servers started showing 3 decimal digits by just appending a `0` at the end. Look at the [data api](status.vatsim.net). All of these freqs are on the 25 kHz spacing. So on vatsim land .420 = .425. You should tune .425 and controllers are getting better at correcting this as well. 
![image](https://user-images.githubusercontent.com/17087998/152018607-46502652-2338-4e33-b40a-b26c550d5cef.png)

**Comment by planetcoops** [comment]
There's more about this issue here: https://forums.vatsim.net/topic/31100-frequency-inaccuracies-in-vatsim-api/

It only affects VATSIM frequencies reported as xxx.x20 and xxx.x70, which should be interpreted as xxx.x25 and xxx.x75 respectively,  the remaining 25kHz steps are valid.
