### ISSUE TITLE
Filing flight plans within the client

### ISSUE THREAD

**Issue by CodeBizarre** [xpilot-project/xpilot#44]
Hello, looking through the changelog I see that at one point in-client flight plans were available, but they were removed due to issues. Are there plans to re-implement this in the future, if not is it open for contribution for a potential PR to add this in better form? It's exceedingly annoying with my setup to have to switch to a web browser for various reasons, such as Widows randomly deciding which browser window on which of 3 monitors to open it on, the fact that Vatsim never keeps me logged in, and the site takes up a whole screen instead of a comfy box (See: vPilot). 

I'm definitely open to work on contributing if possible. Thanks,

**Comment by justinshannon** [comment]
No, flight plans must now be filed using the online web service. This change is not open for discussion.
