### ISSUE TITLE
Volume defaults to 100% when connecting, even when settings is set to lower

### ISSUE THREAD

**Issue by ksgy** [xpilot-project/xpilot#47]
I have my COM1 and COM2 volume set to 30%. When connecting, suddenly all controllers and planes are very loud. If I go to settings and change to eg. 50% then back tio 30% - it gets to "normal" volume.

**Comment by justinshannon** [comment]
Do you have the "Allow aircraft radio stack volume knobs to control radio volume" option enabled?

**Comment by ksgy** [comment]
That was it, thank you! 👍 

Maybe a tip or a note when changing volume (+option mentioned above enabled) would be good feedback for the user to understand how the volumes could be overridden by that option?
