### ISSUE TITLE
Xpilot stuck at the bottom of the screen while connecting

### ISSUE THREAD

**Issue by Dillonshrop** [xpilot-project/xpilot#48]
If you have Xpilot at the bottom of your screen and you click the "connect" button the window pops up but it's hidden and the issue is that there is no way to move the pop-up or the client. So when that happens I have to close Xpilot reconnect with the Xpilot client in the middle of my screen 
![Uploading Screenshot 2022-02-01 200041.png…]()

**Comment by justinshannon** [comment]
The screenshot is broken. Can you upload it again?

**Comment by Dillonshrop** [comment]
![Screenshot 2022-02-01 200041](https://user-images.githubusercontent.com/77188029/152091297-a632fd60-b977-48f6-adad-490dc5952a60.png)
Hope this works

**Comment by Dillonshrop** [comment]
> The screenshot is broken. Can you upload it again?

![Uploading Screenshot 2022-02-01 200041.png…]()

**Comment by justinshannon** [comment]
That's a limitation with how the connection window is implemented. Is there a particular reason why you have the client half-way hidden towards the bottom?

**Comment by Dillonshrop** [comment]
> That's a limitation with how the connection window is implemented. Is there a particular reason why you have the client half-way hidden towards the bottom?

So you're saying there isn't a way to fix it? Maybe yes nobody should have the screen hidden away at the bottom while connecting but for me and I imagine other people... It's force of habit from the older versions of the Xpilot client! I personally keep the Xpilot client at the bottom of my screen on my second monitor so that I can pull up other screens on my second monitor but still have the status of Xpilot showing. For example I can see if I'm hot micing or if my connection dropped out for some reason!

**Comment by justinshannon** [comment]
There’s no need to get offended… I was simply asking so I could get an idea of why you were using the client in that position on your screen. I never said it couldn’t be fixed; it’s just how I implemented the window to begin with. 

The old version will no longer connect to the network.

**Comment by Dillonshrop** [comment]
> There’s no need to get offended… I was simply asking so I could get an idea of why you were using the client in that position on your screen. I never said it couldn’t be fixed; it’s just how I implemented the window to begin with. 
> 
> 
> 
> The old version will no longer connect to the network. 

Oh lol I wasn't offended 😆😳
I totally understand!

**Comment by justinshannon** [comment]
The next version will allow you to drag the client window if the connect window is open.

![8JIJoeos42](https://user-images.githubusercontent.com/3221191/152370190-1bf89964-570d-4ca7-a07d-1c58f83d4f1d.gif)

**Comment by Dillonshrop** [comment]
> The next version will allow you to drag the client window if the connect window is open.
> 
> 
> 
> ![8JIJoeos42](https://user-images.githubusercontent.com/3221191/152370190-1bf89964-570d-4ca7-a07d-1c58f83d4f1d.gif)
> 
> 

Nice that's all that I need!!! Thank you so much! I know it's a silly little thing but it'll improve the quality of life for Xpilot in my opinion!
