### ISSUE TITLE
Settings window may be unusable in certain dual monitor setups

### ISSUE THREAD

**Issue by hotbso** [xpilot-project/xpilot#54]
Not my biggest concern, just to make you aware:
I have a "main" monitor 4K with Windows scaling factor 175% and a secondary monitor 1366x768 no scaling and usually run xPilot on the secondary monitor. The Settings window always opens on the 4K monitor but is too small and shows only about 25% of content. It cannot be resized. One has to drag the xPilot main window onto the 4K monitor and then open settings. Now the Settings window is large and shows all content.

**Comment by justinshannon** [comment]
The DPI issue will be fixed in the next version.
