### ISSUE TITLE
clickable URL

### ISSUE THREAD

**Issue by seelenkrieger** [xpilot-project/xpilot#55]
hey,
in earlier versions it was possible to click on URL's in the ATC atis lines.
for example LOVV has a link for charts and his active sector in it
but it is not clickable anymore
![image](https://user-images.githubusercontent.com/55149789/152511500-229ad698-60f4-4c3c-9ca9-046a56c91e5f.png)

**Comment by justinshannon** [comment]
For xPilot to make them clickable links, the URL needs to be formatted with an `http://` prefix, like: `http://vats.im/lovv-charts`.

**Comment by seelenkrieger** [comment]
thats not possible due euroscope limitation, also prefix like https:// are not working

**Comment by justinshannon** [comment]
The https:// links in the messages from the servers work for me. What OS are you using?

**Comment by seelenkrieger** [comment]
Windows11
https:// message was sendet via Privat chat, if that makes a different
