### ISSUE TITLE
client does not detect xp11

### ISSUE THREAD

**Issue by Gruneau** [xpilot-project/xpilot#56]
Updated to v2.0.0-beta.21 today when prompted after launch of xpilot, the client does not seem to find the running x-plane 11. Mode C button is flashing and it says waiting for X-plane connection.

**Comment by justinshannon** [comment]
Give these steps a try: https://beta.xpilot-project.org/#/faq?id=xpilot-doesn39t-connect-to-x-plane-stuck-on-quotwaiting-for-x-plane-connectionquot

**Comment by Gruneau** [comment]
reinstalled and it solved the issue.. not sure what caused the issue

**Comment by justinshannon** [comment]
It's possible you still had the old plugin installed.
