### ISSUE TITLE
Xpilot client window not showing

### ISSUE THREAD

**Issue by larsrde** [xpilot-project/xpilot#61]
Hi,
I installed Beta21 yesterday, configured everything and was able to fly.
After restart, today the xpilot client window doesn't come up. The xpilot process runs and is visible in the task bar. Right click on the taskbar lets me close the program.
Running as Administrator doesnt make a difference.
Deleting the xpilot plugin dir and re-installing the Beta21 doesnt help, too.
Unfortunately unusable right now.
Just let me know, what information you'd like me to collect.
Lars

**Comment by justinshannon** [comment]
Look for the `AppConfig.json` in `C:\Users\USERNAME\AppData\Local\org.vatsim.xpilot` (replace USERNAME with your actual computer username), open it with a text editor and paste the `WindowConfig` section from the config file here.

It should look something like this:

```
"WindowConfig": {
	"Height": 281,
	"Maximized": false,
	"Width": 882,
	"X": 593,
	"Y": 500
}
```

**Comment by larsrde** [comment]
Hi, seems like it has moved very far right on the x axis.
I will let you know if setting X to some more reasonable value helped.

`    "WindowConfig": {
        "Height": 678,
        "Maximized": false,
        "Width": 1203,
        "X": 4557,
        "Y": 683
    }, `

**Comment by larsrde** [comment]
So, it's visible now.
This behavior could be observed also with the old 1.3 client. But the difference is, that with the old client re-arranging all windows (or temporarily changing the screen resolution) helped to move it back into the visible area. None of the old tricks did it here with the Beta21.
Anyways. Thanks.
Lars

**Comment by justinshannon** [comment]
This should hopefully be fixed in the next version (9fb1bcb614dae5506a81f576cc06c51192a53d24). My theory is that the window position is getting changed to something outside the available screen bounds (i.e. the client window is getting moved to a position that is not visible on your monitors). This fix should re-center the window if it moves outside the available screen bounds.

**Comment by larsrde** [comment]
It's easily reproducible:

Two screens: S1 for XP11, S2 for the xpilot client and other tools.

- Say S1 is 4K, but you run x-plane in a lower resolution.
- When XP starts all windows are moved around, also on S2.
- After you re-arranged everything and stopped XP, S1 is switching back to a higher resolution, and this moves the applications out of the boundaries of S2.

**Comment by justinshannon** [comment]
@larsrde, can you give this version a try? Just install it directly over your existing b21 installation. Let me know if this fixes the issue.

https://xpilot-project.org/installers/xPilot-2.0.0-beta.21-windows-x64-installer.exe

**Comment by larsrde** [comment]
Download and installed the other b21.
Tested a little bit. Screen1 4K, Screen 2 1920x1080

In general, for all usual use cases it's working fine. It moves around on the second screen, but never exceeds the boundaries.

There is just one scenario when it disappeared into the invisible:

1. Both, xpilot client and XP11 are running.
2. XP is running in 4K on Screen1.
3. xpilot client is roughly centered on Screen 2.
4. Now changing the graphics settings of XP11. Changing resolution DOWN to 1920x1080.
Voila. Xpilot client insivible.

**Comment by justinshannon** [comment]
Thanks for giving it a try. I don't have a 4K screen, so I probably won't be able to do much else to the logic without a way to test it.
