### ISSUE TITLE
xplane crash beta 22 

### ISSUE THREAD

**Issue by donks** [xpilot-project/xpilot#65]
Able to crash xplane when connected to vatsim (in observer mode) by attempting to replay a flight.

**Comment by jersyetwin** [comment]
Im also able to produce an Xplane crash if I go in and manually disable this plugin, then upon reenabling it during the session.

**Comment by IBAV8N** [comment]
As above, in observer mode if I disconnect from xpilot, x-plane freezes. Linux.

**Comment by jersyetwin** [comment]
Also erroring out and closing Xplane when clicking on the xpilot disconnect button during the session.  Was attempting to go to settings to change a different region, then reconnect.

**Comment by justinshannon** [comment]
This is fixed in beta 23.
