### ISSUE TITLE
Serious Problem Does Not Transmit Or Receive Audio

### ISSUE THREAD

**Issue by GaboPilotCPO** [xpilot-project/xpilot#66]
Hello everyone, I'm Gabriel from Chile, I'm having problems using the new version of xPilot 2.0.0-beta.22 (beta.21 and beta.20), since I can't listen or transmit audio through the xPilot connection. With the previous version of xPilot (1.3.38) I had no problem, but when upgrading I can't use the aircraft radio (A321 Neo - Toliss). Please your help, I have tried everything but nothing solves it. Thanks a lot.

**Comment by DominikTV** [comment]
Well _what_ do you have tried? You have checked your audio devices in the xpilot settings? Tried different audio-api? Set a PTT-Button in X-Plane?

**Comment by justinshannon** [comment]
Can you upload the most recent AFV log in `C:\Users\USERNAME\AppData\Local\org.vatsim.xpilot\AfvLogs`?

**Comment by justinshannon** [comment]
Closing this due to no response. If you're still having issues, I would suggest joining the xPilot Discord for a more prompt response.
