### ISSUE TITLE
Towerview broken 

### ISSUE THREAD

**Issue by detheridge02** [xpilot-project/xpilot#69]
xpilot Version : beta 26 
ES version : 3.2a r33
The latest beta seems to have broken towerview again (possibly due to fastpacket work). Previous versions still showed moving traffic when connected to VATSIM via an ES proxy connection

**Comment by justinshannon** [comment]
Towerview with EuroScope does not currently work:

`Users who use virtual tower functionality utilizing a proxy server with vSTARS will need to update vSTARS. Virtual towers via a proxy server with Euroscope will not function until Euroscope is updated.`

https://forums.vatsim.net/topic/32619-vatsim-announces-velocity-release-date-and-rollout-plan/

**Comment by detheridge02** [comment]
It worked fine in previous versions of xpilot. Towerview with vPilot didn’t work though

**Comment by justinshannon** [comment]
Did you not read what I posted? Here, I'll put it in bold for you:

**Virtual towers via a proxy server with Euroscope will not function until Euroscope is updated.**

**Comment by detheridge02** [comment]
As a streamer and controller I can categorically state, as can other streamers, that prior to the latest beta towerview was working perfectly well proxied via ES using the old 5s packets (nobody is expecting fastpackets until ES is ‘fixed’ whenever that may be). There was some odd stepped climb weirdness but traffic WAS moving on the ground. 

My twitch channel is NorthernAviation, check out my recent vods all of which use towerview via the latest beta of xpilot available at the time of stream. 
Some other streamers who also use xPilot for their stream towerviews are ste_plays, hinshee and followthegreens, all of whom moved to xpilot / XPL when vpilot stopped working when Velocity was released. 

My last vod controlling EGLL_S_TWR https://www.twitch.tv/videos/1295711836

 

Looking through the repo (former C++ developer now a senior Development Team Manager for one of the UK’s leading FinCo’s) changes were made 8 days ago in areas surrounding fastpackets, which is great and no doubt the ES issue is more a hinderance to yourself than it is to us controllers. If you want to send me the previous beta I can demonstrate (as can the vods above) a working towerview. 



Heck, despite the rude reply below I’ll happily test any changes. Don’t be as quick to dismiss a GitHub issue as being from some kid playing on a computer that mummy or daddy bought them. 

 

That all being said I’m sure I echo the sentiments of pilots and controllers worldwide in thanking you for all your hard work on xPilot
