### ISSUE TITLE
xPilot-2.0.0-beta.26-linux-x64 won't start on Centos8

### ISSUE THREAD

**Issue by ftivano** [xpilot-project/xpilot#70]
The installation process seems to work since the installation wizard finish asking "Launch xPilot"  but application wont' start with
the following message:

 /tmp/.mount_xPilotgEoCY1/AppRun.wrapped: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_xPilotgEoCY1/AppRun.wrapped)

Latest GLIBC available version for CENTOS8 is glibc-2.28-189.

**Comment by justinshannon** [comment]
Is this your first time trying to install xPilot? Or did an earlier version work for you?

**Comment by justinshannon** [comment]
I'm looking to setup a test environment, but I'm not familiar with the CentOS distro. Do you have CentOS Stream 8 installed?

**Comment by ftivano** [comment]
Sure I have! my workstation is an to date CentOS Stream 8, just lil customized,  but  I  could deploy new clean VM from scratch in a bit just for this project, 'll be happy to cooperate.

**Comment by ftivano** [comment]
Hello, after few months i saw my old xpilot 2.34 client version is not supported on vatsim anymore.
are xPilot releases no longer available for linux glibc 2.28 ?

**Comment by justinshannon** [comment]
Unfortunately, that is correct. Github depreciated (and removed) the Ubuntu 18.04 runner image, so xPilot is now compiled with 20.04.

https://github.com/actions/runner-images/issues/6002

**Comment by ftivano** [comment]
Bad news :( there is any changes to build with latest xpilot version with  linux glibc 2.28 from sources ? I would l try to do it if possible.
