### ISSUE TITLE
[FEATURE REQUEST] Addition to the new Selcal feature

### ISSUE THREAD

**Issue by WizballCvS** [xpilot-project/xpilot#71]
Suggestion to this new selcal feature.

Maybe add a way for xpilot to detect that the aircraft is supporting selcal. So you dont need to manually disable the selcal alert in xpilot to avoid dual alert from xpilot and the aircraft.
When xpilot detect that the aircraft is supporting selcal, xpilot will not play the selcal alert.

I.e. the CL650 will be adding native audio alert support, so no need for the double-alerting.

Could maybe also just be a writable dataref i.e. xpilot/selcal_mute = 0|1 or xpilot/selcal_mute_override = 0|1 . Something like that.

**Comment by justinshannon** [comment]
I’m not sure how xPilot would know if the aircraft supports SELCAL. Specifically, does the CL650 have a dataref that indicates this?

**Comment by mloftis** [comment]
There totally could be. The devs for the Challenger are fully aware of this request/ticket. I've passed this along...

**Comment by mloftis** [comment]
The idea here though was for the aircraft to be able to hit your data ref and toggle the xPilot SELCAL alert

**Comment by skiselkov** [comment]
@justinshannon Hey there, CL650 dev here. The ideal situation would be if there was a dataref *the aircraft* would signal to xPilot whether native SELCAL audio is implemented, not the other way around. That way, you won't have to worry about it - simply expose the override feature to us and we'll take care of the rest.

**Comment by justinshannon** [comment]
A new dataref called `xpilot/selcal_mute_override` will be available in the next version. Setting it to a value of `1` will disable the SELCAL sound in the client.
