### ISSUE TITLE
Version 2.0.0-beta.27 Voice Server error : Timeout

### ISSUE THREAD

**Issue by Olli3001** [xpilot-project/xpilot#73]
Hi,
The problem is that the error comes every minute: Voice Server Timeout. After about 3-4 seconds the connection will be restored. 

System WIN 10
![Voice Server Timeout](https://user-images.githubusercontent.com/100069110/154837257-e3a5e359-704f-4979-a761-c9e000f30f87.PNG)

**Comment by LukasLorason** [comment]
Choose another server

**Comment by Olli3001** [comment]
> Choose another server

Changing the server doesn't change anything. The error persists.

**Comment by justinshannon** [comment]
Unfortunately, there is only one voice server and if you don't have a stable connection to it, you will notice timeouts like this.
