### ISSUE TITLE
Can´t choose Aircraft Type

### ISSUE THREAD

**Issue by LukasLorason** [xpilot-project/xpilot#74]
Hello I have a new issue, I can´t choose my Aircraft type on X Pilot. It makes no proposal. And when I want to connect with the correct Type code in the box ít says "The aircraft type code you entered appears to be invalid. Using an invalid type code can make your aircraft render incorrectly for other users." I´m trying to connect since 2 hours.......... please help.

**Comment by justinshannon** [comment]
This issue should have been resolved yesterday. It was a server glitch. Are you _still_ getting the invalid type code error?

**Comment by LakshJ9** [comment]
@justinshannon yes sir, this issue was resolved yesterday… I flew in the evening and saw that the options were available… thank you!
