### ISSUE TITLE
Conect button doesn't working

### ISSUE THREAD

**Issue by vini963** [xpilot-project/xpilot#75]
The conect button is unavailable after last update, I can't conect in VATSIM Network.

**Comment by MattBerks** [comment]
I also have this problem.

**Comment by wiggleforlife** [comment]
Please try [these troubleshooting steps](https://beta.xpilot-project.org/#/faq?id=xpilot-doesn39t-connect-to-x-plane-stuck-on-quotwaiting-for-x-plane-connectionquot). If these do not work, upload your X-Plane Log.txt (in the folder where X-Plane.exe/X-Plane.app/X-Plane.x86-64 is located). 

If you see a multiplayer machine sending data but not responding in the X-Plane network settings (see attached image), please uninstall xPilot and try [beta 22.](https://github.com/xpilot-project/xpilot/releases/tag/v2.0.0-beta.22)

![X-Plane Network tab screenshot](https://media.discordapp.net/attachments/787750441786146826/944718424658030632/unknown.png?width=578&height=349)

**Comment by vini963** [comment]
The problem has been solved using the xPilot beta 22. It's all right. Thanks!!!
