### ISSUE TITLE
How should I download the new Xpilot

### ISSUE THREAD

**Issue by Mathi999** [xpilot-project/xpilot#76]
Does anyone have a good instruction for me?

Thank you Mathis

**Comment by wiggleforlife** [comment]
If you have the old one installed (assuming you are on Windows), open Control Panel, go to Programs & Features -> Uninstall a Program and uninstall xPilot.

After opening the [releases page](https://github.com/xpilot-project/xpilot/releases), Hit the "Assets" button on either the latest or beta 22. Download the installer suitable for your platform.

Please read the [documentation](https://beta.xpilot-project.org/#/?id=what-is-xpilot) before you post an issue.
