### ISSUE TITLE
b2v29: xPilot + xPlane crashes

### ISSUE THREAD

**Issue by ansgar-hoffmann** [xpilot-project/xpilot#81]
After updating to version beta 2 v 29 xPlane crashes with xPilot. You can download both crash reports here: [crash-reports-b2v29.zip](https://www.dropbox.com/s/wrqwh71j9i7ilia/crash-reports-b2v29%20macOS.zip?dl=0)

**Comment by ansgar-hoffmann** [comment]
@justinshannon For the first look it with beta 31 it seems to be good. I will give more information, when I can do a whole flight, a few days later ...

**Comment by ansgar-hoffmann** [comment]
I've done a short flight from EDDP to EDDF, everything seems to be fine at me. Strange, at the beginning of EDDP and the flight along there where no stations in "nearby ATC"-window within XPlane Plugin. After the landing in EDDF the stations were there. I logged in again in EDDS, there was the stations like it should be.

**Comment by justinshannon** [comment]
I'm going to close this issue since the crash has been resolved. If you continue to have issues with the nearby ATC window, please open a new issue.
