### ISSUE TITLE
Audio problems on Ubuntu

### ISSUE THREAD

**Issue by slimit75** [xpilot-project/xpilot#88]
I am having an issue with my audio, and it seems to occur at random and sometimes cannot be fixed until one restarts xPilot.

I am running Ubuntu 21.10, and occasionally xPilot will stop picking up my mic. When it does this, it stops playing audio as well, so my only clue that something is wrong is if the radio seems to be silent for an unusual period of time. 

In the settings I have multiple mic options (despite one mic), and on some occasions cycling through all of them will fix my problem temporarily. Usually the options 'default' or 'pulse' work, but both will eventually stop picking up my mic. This seems to be exclusive to xPilot, as I can still hear other apps, and others can still hear me just fine on discord. It happens frequently enough to the point where it happens on every flight I attempt to do, and the attempted workarounds I mentioned above will keep it working from anywhere between a few minutes to the rest of the flight.

Sorry if this was really confusing, I would attach a photo of my settings right now but xPilot currently isn't launching and I haven't restarted my computer yet. 

EDIT: Restarted my computer, here are my audio settings and the options I have for input devices.
![image](https://user-images.githubusercontent.com/45863722/157566840-5c4ac9ac-d476-4494-ac4d-d0e75100d481.png)
![image](https://user-images.githubusercontent.com/45863722/157566973-0350f42b-662e-4c2f-a3a7-79bf6c539829.png)

**Comment by justinshannon** [comment]
The next time this happens, can you upload the AFV log found in `~/.local/share/org.vatsim.xpilot/AfvLogs`?

**Comment by slimit75** [comment]
Sure!

**Comment by slimit75** [comment]
Was just able to recreate it, here is the AFV log
[AfvLog-20220326-131641.txt](https://github.com/xpilot-project/xpilot/files/8355535/AfvLog-20220326-131641.txt)

**Comment by slimit75** [comment]
After CTP, I think its safe to say it is an issue on my end. While it ran mostly smooth, it did stop picking up my mic once which was easily resolved by selecting the same output as the input.

**Comment by justinshannon** [comment]
I would agree. The log doesn’t show anything out of the ordinary that would suggest anything failing on the xPilot side. I’ll close this for now.
