### ISSUE TITLE
Download Error

### ISSUE THREAD

**Issue by KristN1** [xpilot-project/xpilot#89]
First time installing xPilot, after being choosing to install the CSL aircraft model, the download stops pretty much instantly with this error.
![image](https://user-images.githubusercontent.com/26331401/157744839-ad397a70-d432-4fdb-bd59-39dd1ed3620d.png)
using v2.0.0-beta32

**Comment by justinshannon** [comment]
See: https://github.com/xpilot-project/xpilot/issues/87#issuecomment-1062962607
