### ISSUE TITLE
Allow to relocate the notification panel

### ISSUE THREAD

**Issue by acaproni** [xpilot-project/xpilot#90]
The notification panel is displayed in the top right corner and cannot be relocated. That position can be uncomfortable with big monitors or with an home cockpit where that corner is partially covered by the overhead panel.

The settings should allow to relocate the notification panel to all the corners (i.e. top-left, bottom-left, top-right, bottom-right) and the center.
The possibility to drag the panel on the desired position would be great  but it might be too much work and not worst the case.

**Comment by justinshannon** [comment]
Additional position options will be available in the next version; top left, top right, bottom left and bottom right.

**Comment by justinshannon** [comment]
This is now available in Beta 33.
