### ISSUE TITLE
xPilot cannot download CLS Aircraft set

### ISSUE THREAD

**Issue by a-x-** [xpilot-project/xpilot#91]
https://xpilot-project.org/api/v3/DownloadModels
404

MacOS

latest version (xPilot v2.0.0-beta.32)

![4C8AD9C5-AE7A-40AF-9A12-E45417DC39D8](https://user-images.githubusercontent.com/6201068/159651470-52cb76a0-c485-4457-8e36-f3b8153e696f.jpeg)

**Comment by a-x-** [comment]
thank you @mloftis, 
do you know, can I load these 'cls' manually? May be I can run my own local server with files the client need?

**Comment by a-x-** [comment]
hm, I'll try another client: XSquawkBox as it mentioned in this csl package. I hope it'll work w/o problems, 
currently I don't want to figure out what the csl

**Comment by mloftis** [comment]
You just need to install them (extract them) and tell xPilot where they live.  The dev has a workaround in the repo that'll be included in the next release (basically requiring some back and forth to verify you're a human).  The xPilot client just grabs a ZIP they made, extracts it, and sets the CSL path.  (instructions for that in the second link)

**Comment by mloftis** [comment]
xPilot is just trying to make it easier by doing steps for you.  You can use whatever CSL package(s) you like with xPilot.  Just have to tell it where they live.

**Comment by a-x-** [comment]
ok, i'll try,
btw, XSquawkBox doesn't work (failing connecting...)

**Comment by mloftis** [comment]
Yeah if you'd read/looked, they're done since the Velocity switchover.  It is well published on Vatsim's site, in their forums, and with their Velocity announcement.  I'm guessing that it's a dead project...last release was sometime in 2020.

**Comment by justinshannon** [comment]
The CSL download has been made available again in Beta 33.
