### ISSUE TITLE
Qt Framework -> Qt Creator

### ISSUE THREAD

**Issue by didierma34** [xpilot-project/xpilot#92]
Hello,
You use Qt Framework, but there is no ".pro" file to use with Qt Creator (open source).
Which software do you use to maintain and write code ? 
thank's

**Comment by justinshannon** [comment]
I use Qt Creator. xPilot is a CMake project, which is why there are no .pro files.

**Comment by didierma34** [comment]
Ok...
Do I download something else in QT Creator to open a Cmake project ?
If yes, which 3rd part ?

Thanks


Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by justinshannon** [comment]
No, I strictly use QT Creator.
