### ISSUE TITLE
Severe delay between sim and xPilot

### ISSUE THREAD

**Issue by slimit75** [xpilot-project/xpilot#93]
While attempting to recreate #88, I ran into another issue as well: there seems to be a severe delay between actions done in X-Plane and them being reflected in xPilot in the latest version. This affects all actions done in the sim, such as changing frequencies, audio panel selections, and even the push to talk key. Commands do not seem to work for setting new frequencies. 

In the video below, you can see how the TX overlay in the sim comes up but not in xPilot itself. At the very beginning of the video, you can see how the TX light does light up, but this was from a prior attempt.
https://user-images.githubusercontent.com/45863722/160244736-e0d0ef3c-298e-45e0-a761-2ec0e6ee6113.mp4

Here are all of the logs from xPilot in addition to the X-Plane log:
[PluginLog-20220326-141626.txt](https://github.com/xpilot-project/xpilot/files/8355676/PluginLog-20220326-141626.txt)
[NetworkLog-20220326-141626.txt](https://github.com/xpilot-project/xpilot/files/8355677/NetworkLog-20220326-141626.txt)
[AfvLog-20220326-141626.txt](https://github.com/xpilot-project/xpilot/files/8355678/AfvLog-20220326-141626.txt)
[Log.txt](https://github.com/xpilot-project/xpilot/files/8355675/Log.txt)

**Comment by justinshannon** [comment]
Interactions like changing frequencies and activating PTT are all done using X-Plane's UDP protocol. This is the first time I've heard of this happening, which makes me think it's something on your local network that is causing this happen.

What is your "UDP Rate" in the Data Output settings in X-Plane? The default value is 20 packets/second.

**Comment by slimit75** [comment]
UDP rate is the default 20 packets/second, will try again after a fresh reinstall of everything

**Comment by slimit75** [comment]
Reinstalling (mostly) everything didn't help, although I did find the issue. It seems to only occur when "Transmit to a single mapping app" and "Use Control Pad as an IOS" are checked. I wasn't using a mapping app at the time, so I have no idea if the delay is mitigated when they are actually being used, but it was my fault. Apologies
