### ISSUE TITLE
Focusrite Scarlett (8i6) not working with audio I/O

### ISSUE THREAD

**Issue by ruthieeeeee** [xpilot-project/xpilot#97]
Simple, the device shows up in MME and DirectSound but XPilot does not receive any signal from the device or allow sound output. I am running the latest version of xpilot and windows 11.

**Comment by floyedxman** [comment]
does it run on Win10

**Comment by ruthieeeeee** [comment]
i would be able to answer that question if i used windows 10, but from what i can remember yes

**Comment by justinshannon** [comment]
I do not have access to this piece of equipment, so I will not be able to provide any sort of support for it. Sorry.
