### ISSUE TITLE
xPilot 2.0.0-beta.34 Crashes Xplane11 Mid-Flight

### ISSUE THREAD

**Issue by aflopex777** [xpilot-project/xpilot#99]
xPilot 2.0.0-beta34 crashed xplane11 in the middle of the flights. I am not able to complete any flight anymore with xpilot. I been told to downgrade and not use beta versions but all the versions available are beta. 

![image](https://user-images.githubusercontent.com/104601927/165863291-6c015292-ff14-4877-8b1c-a1ccafa2e9f5.png)

[Log (3).txt](https://github.com/xpilot-project/xpilot/files/8587221/Log.3.txt)

**Comment by justinshannon** [comment]
I am closing this one for now. If it happens again, please re-open and provide the requested log and crash files.
